/*
 *  Author: Vlad Seryakov vseryakov@gmail.com
 *  backendjs 2018
 */
'use strict';

const logger = require(__dirname + '/../logger');
const lib = require(__dirname + '/../lib');
const db = require(__dirname + '/../db');
const api = require(__dirname + '/../api');

/**
  * @module api/users
  */

const mod =

/**
 * ## Users table management and DB operations
 *
 * This is a wrapper around users table to support multiple databases with the same interface, makes it easy to
 * find users by id or login.
 *
 * Supports simple TOTP and email MFA code verification.
 *
 * User cookie sessions are stored in the `sessions` columns as a list of expiration time in ms. Every login or logout removes
 * expired sessions from the list. To login a session must be present in the list.
 *
 * API token based authentication is implemented as well, the `login` and `secret` are generated by the {@link module:api/users.prepareToken},
 * the id can be provided or generated.
 *
 * Real users can have more than one API token by saving api tokens with the same user id.
 *
 * To enable it just add a table name of your choice to the bkjs.conf
 *
 * ```
 * api-users-table = users
 * ```
 *
 * Users and tokens can be created via shell commands:
 *
 * ```sh
 * # bksh -user-add login admin name admin secret XXXXX roles admin
 * '136ea1b9fb1778bd2d37096d'
 *
 * # bksh -user-add-token name test flags api -prefix api_
 * 'api_7e717a99e4b642ce88010629d32921b7caf92f4d165c46f59f983f880aa25c78'
 * ```
 */
module.exports = {
    name: "api.users",

    /**
     * Module specific config parameters
     * @var {object[]}
     */
    args: [
        { name: "err-(.+)", descr: "Error messages for various cases" },
        { name: "table", descr: "Database table to create and use for users" },
        { name: "max-length", type: "number", min: 10, descr: "Max length for user name, login" },
        { name: "mfa-age", type: "int", min: 30000, descr: "Age in ms of a MFA code" },
    ],

    /**
     * Age of a MFA code in ms
     * @var {number}
     * @default
     */
    mfaAge: 600000,

    /**
     * Table to create and use for users, it is an instance of {@link DbTable} and uses the default {@link module:api/users.schema} property.
     * @var {string}
     * @default
     */
    table: "",

    /**
     * Max length for user name, login
     * @var {number}
     * @default
     */
    maxLength: 140,

    /**
     * Default users table schema, each column is represented by a {@link DbTableColumn} type.
     * @property {object} schema
     * @property {string} schema.login - primary key, user email, name or other unique identifier
     * @property {string} schema.id - unique auto-generated UUIDv4
     * @property {string} schema.name - full user name
     * @property {string[]} schema.roles - list of roles for authorization
     * @property {string[]} schema.flags - tags, feature flags...
     * @property {string} schema.secret - hashed user password
     * @property {string} schema.topt_secret - generated secret for TOTP MFA encoded as base32, the present of the sedret will require TOTP code on every login
     * @property {string} schema.mfa_code - used to enforce MFA verification and keep the last code sent, to enable set any non-empty value,
     * when sent it is saved in the format: `code,expires,type`, a code, expiration in ms, sent method(email,text..)
     * @property {string} schema.pushkey - can be used for push notifications, tokens: [service://]token[@appname]
     * @property {string} schema.passkey - can be used for passkey verifications
     * @property {number[]} schema.sessions - list of sessions, expiration time
     * @property {number} schema.create_time - create time in milliseconds
     * @property {number} schema.update_time - last modified time, auto saved
     * @property {number} schema.access_time - last access time
     * @property {number} schema.login_time - last time user logged in
     * @property {number} schema.expire_time - deny access if this value is before current date, ms
     */

    schema: {
        login: {
            primary: 1,
            keyword: true,
            length: 1,
            check: {
                max: 1
            },
        },
        id: {
            type: "uuid",
            index: 1,
            keyword: true,
            api: {
                pub: true,
            },
            _$db: { index: "UNIQUE" },
            _$dynamodb: { projections: "ALL" },
        },
        name: {
            type: "str",
            length: 1,
            check: {
                not_empty: true,
                max: 1
            },
            api: {
                pub: true,
            }
        },
        roles: {
            type: "set",
            convert: {
                lower: true,
            },
            api: {
                internal: true,
            }
        },
        flags: {
            type: "set",
            check: {
                max: 1
            },
        },
        create_time: { type: "now", readonly: 1 },
        update_time: { type: "now" },
        access_time: { type: "bigint" },
        login_time: {
            type: "bigint",
            api: {
                internal: true,
                priv: true
            },
        },
        expire_time: {
            type: "bigint",
            api: {
                internal: true,
                priv: true
            },
        },
        secret: {
            type: "str",
            api: {
                priv: true
            },
        },
        totp_secret: {
            type: "text",
        },
        mfa_code: {
            type: "text",
            api: {
                internal: true,
                priv: true,
            },
        },
        pushkey: {
            type: "text",
            api: {
                priv: true,
            },
            check: {
                max: 4096
            }
        },
        passkey: {
            type: "text",
            api: {
                internal: true,
                priv: true,
            },
            check: {
                max: 4096
            }
        },
        sessions: {
            type: "set",
            split: {
                datatype: "int",
            },
            api: {
                internal: true,
                priv: true,
            },
        }
    },

    errInvalidLogin: "The login is required",
    errInvalidName: "The name is required",
    errInvalidParams: "No username or id provided",
    errInvalidId: "Invalid user id provided",
    errInvalidSession: "Authentication is required",
    errInvalidCode: "Verification code is required",

};

mod.configure = function(_options, callback)
{
    if (this.table) {

        for (const col of Object.values(this.schema)) {
            if (col.length === 1) col.length = this.maxLength;
            if (col.check?.max === 1) col.check.max = this.maxLength;
        }
        this.tables = { [this.table]: this.schema };
    }

    callback();
}

/**
 * Returns a user record by login or id
 * @param {object|string} query - user id or login or { id, login }
 * @param {object} [options]
 * @param {function(err:object, user:object)} callback returning found record
 * @memberof module:api/users
 * @method get
 */
mod.get = function(query, options, callback)
{
    if (typeof options === "function") callback = options, options = null;

    if (typeof query === "string") {
        query = { [lib.isUuid(query) ? "id" : "login"]: query };
    }

    if (query?.login) {
        db.get(mod.table, { login: query.login }, callback);
    } else

    if (query?.id) {
        const opts = {
            sort: "id",
            cacheKeyName: "id",
            count: 1,
            first: 1,
        };
        db.select(mod.table, { id: query.id }, opts, callback);
    } else {
        callback();
    }
}

/**
 * Async version of the {@link module:api/users.get} method
 * @param {object|string} query
 * @param {object} [options]
 * @returns {{err:object, data:object}}
 * @example
 * const { err, data } = await api.users.aget("john@mail.com");
 * @memberof module:api/users
 * @method aget
 * @async
 */
mod.aget = function(query, options)
{
    return new Promise((resolve, _reject) => {
        mod.get(query, options, (err, data, info) => {
            resolve({ err, data, info });
        });
    });
}

/**
 * Registers a new user, returns new record in the callback,
 * @param {object} query - user record
 * @param {object} [options]
 * @param {function(err:object, user:object)} callback returning new user record
 * @memberof module:api/users
 * @method add
 * @example
 * lib.prepareSecret("secret....", (err, secret) => {
 *     api.users.add({ login: "john@mail.com", name: "John", secret }, (err) => {
 *     });
 * });
 */
mod.add = function(query, options, callback)
{
    if (typeof options === "function") callback = options, options = null;
    if (!query?.login) {
        return lib.tryCall(callback, { status: 400, message: mod.errInvalidLogin });
    }
    if (!query.name) {
        return lib.tryCall(callback, { status: 400, message: mod.errInvalidName });
    }

    var opts = { result_query: 1, first: 1 };
    if (!this.isUuid(query.id)) query.id = undefined;

    db.add(mod.table, query, opts, (err, row, info) => {
        if (err) return lib.tryCall(callback, err);

        Object.assign(query, row);
        lib.tryCall(callback, err, query, info);
    });
}

/**
 * Async version of the {@link module:api/users.add} method
 * @param {object|string} query
 * @param {object} [options]
 * @returns {{err:object, data:object}}
 * @example
 * const { err, secret } = await lib.aprepareSecret("secret....");
 * const { err, data } = await api.users.aadd({ login: "john@mail.com", name: "John", secret });
 * @memberof module:api/users
 * @method aadd
 * @async
 */
mod.aadd = function(query, options)
{
    return new Promise((resolve, _reject) => {
        mod.add(query, options, (err, data, info) => {
            resolve({ err, data, info });
        });
    });
}

/**
 * Updates an existing user by login
 * @param {object} query
 * @param {object} [options]
 * @param {function(err:object, user:object)} callback returning updated user record
 * @memberof module:api/users
 * @method update
 * @example
 * api.users.update({ login: "john@mail.com", name: "John" }, lib.log);
 */
mod.update = function(query, options, callback)
{
    if (typeof options === "function") callback = options, options = null;
    if (!query?.login) {
        return lib.tryCall(callback, { status: 400, message: mod.errInvalidLogin });
    }

    var opts = { returning: "*", first: 1 };
    query = Object.assign({}, query);

    if (!query.name) query.name = undefined;
    if (!this.isUuid(query.id)) query.id = undefined;

    db.update(this.table, query, opts, callback);
}

/**
 * Async version of the {@link module:api/users.update} method
 * @param {object} query
 * @param {object} [options]
 * @returns {{err:object, data:object}}
 * @example
 * const { err, data } = await api.users.aupdate({ login: "john@mail.com", name: "John" });
 * @memberof module:api/users
 * @method aupdate
 * @async
 */

mod.aupdate = function(query, options)
{
    return new Promise((resolve, _reject) => {
        mod.update(query, options, (err, data, info) => {
            resolve({ err, data, info });
        });
    });
}

/**
 * Deletes an existing user by login or id, no admin checks, returns the old record in the callback
 * @param {object|string} query - user id or login or { id, login }
 * @param {object} [options]
 * @param {function(err:object, user:object)} callback
 * @memberof module:api/users
 * @method del
 * @example
 * api.users.del("john@mail.com", lib.log);
 *
 * api.users.del({ login: "john@mail.com" }, lib.log);
 */
mod.del = function(query, options, callback)
{
    if (typeof options === "function") callback = options, options = null;
    if (typeof query === "string") {
        query = { [this.isUuid(query) ? "id" : "login"]: query };
    }
    var opts = { returning: "old", first: 1 };

    if (query?.login) {
        db.del(this.table, query, opts, callback);
    } else

    if (query?.id) {
        mod.get(query.id, (err, row) => {
            if (!row) return callback(err, { status: 404, message: this.errInvalidId });

            query.login = row.login;
            db.del(this.table, query, opts, callback);
        });
    } else {
        lib.tryCall(callback, { status: 400, message: this.errInvalidParams });
    }
}

/**
 * Async version of the {@link module:api/users.del} method
 * @param {object|string} query
 * @param {object} [options]
 * @returns {{err:object, data:object}}
 * @example
 * const { err, data } = await api.users.adel("john@mail.com");
 *
 * const { err, data } = await api.users.adel({ login: "john@mail.com" });
 * @memberof module:api/users
 * @method adel
 * @async
 */

mod.adel = function(query, options)
{
    return new Promise((resolve, _reject) => {
        mod.del(query, options, (err, data, info) => {
            resolve({ err, data, info });
        });
    });
}

/**
 * Returns true of the given id is a valid user uuid,
 * it is {@link module:lib.isUuid} with optional user's table id column prefix
 * @param {string} id
 * @returns {boolean}
 * @method isUuid
 * @memberof module:api/users
 *
 */
mod.isUuid = function(id)
{
    return lib.isUuid(id, this.tables?.[this.table].id?.prefix);
}

/**
 * Cleanup user record to be returned by API endpoint, remove all internal and priv properties
 * @param {object} user
 * @returns {object}
 * @method clearup
 * @memberof module:api/users
 */
mod.cleanup = function(user)
{
    return db.cleanupResult(mod.table, user);
}

/**
 * Verify user by login and secret
 * @param {object} query - an object with { login|id, secret } properties for login
 * @param {function(err:object, user:object)} callback
 * @memberof module:api/users
 * @method checkSecret
 * @example
 * api.users.checkSecret({ login: "john", secret : "..." }, (err, user) => {
 *     if (err) return
 * })
 */
mod.checkSecret = function(query, callback)
{
    mod.get(query, (_err, user) => {
        if (!user) {
            return lib.tryCall(callback, { status: 401, message: mod.errInvalidLogin });
        }

        lib.checkSecret(user.secret, query.secret, (_err, ok) => {
            lib.tryCall(callback, ok ? null : { status: 401, message: mod.errInvalidLogin }, user);
        });
    });
}

/**
 * Async version of {@link module:api/users.checkSecret}, verify user by login and secret
 * @param {object} query - an object with { login|id, secret } properties for login
 * @returns {{err:object, data:object}}
 * @memberof module:api/users
 * @method acheckSecret
 * @async
 * @example
 * const { err, data } = api.users.acheckSecret({ id: "...", secret : "..." });
 */
mod.acheckSecret = function(query)
{
    return new Promise((resolve, _reject) => {
        mod.checkSecret(query, (err, data) => {
            resolve({ err, data });
        });
    });
}

/**
 * Verify current cookie session and set the user in the context on success, this can be used standalone or as middleware
 * @param {RequestContext} context
 * @param {function(err:object, user:object)} callback
 * @memberof module:api/users
 * @method verifySession
 */
mod.verifySession = function(context, callback)
{
    const session = api.session.parse(context);
    if (!session) {
        logger.debug("verifySession:", mod.name, "nosession:", context);
        return callback({ status: 401, message: mod.errInvalidSession });
    }

    mod.get(session.id, (err, user) => {
        if (err) return callback(err);

        if (!user) {
            logger.debug("verifySession:", mod.name, "expired:", context);
            return callback({ status: 401, message: mod.errInvalidSession });
        }

        if (user.expire_time > 0 && user.expire_time < Date.now()) {
            logger.debug("verifySession:", mod.name, "expired:", context, user.id, user.name, user.expire_time);
            return callback({ status: 401, message: mod.errInvalidSession });
        }

        if (!lib.includes(user.sessions, session.exp) || !api.session.verify(context, user.secret)) {
            logger.debug("verifySession:", mod.name, "invalid:", context, user.id, user.name, user.sessions);
            return callback({ status: 401, message: mod.errInvalidSession });
        }

        context.user = user;

        callback(err, user);
    });
}

/**
 * Verify API token from Authorization header and sets user in the context on success, this can be used standalone or as middleware.
 *
 * It must be in format: `Authorization: Basic base64(token)` or `Authorization: Bearer token`,
 *
 * An API token is created for corresponding columns in the user table, see {@link module:api/users.prepareToken}:
 * - `id`: generated UUIDv4 by {@link module:lib.uuid} as ussual or can be an existing user id to link multiple tokens for a user
 * - `login`: generated UUIDv4 by {@link module:lib.uuid}, unique primary key
 * - `secret`: generated UUIDv4 by {@link module:lib.uuid}
 * - __send the token as `${login}${secret}` back to user via secure method, like TLS....__
 * - hash the secret with SHA256 and store in the DB
 *
 * Verification is done the following way:
 * - get a user record from DB by `token.substr(0, 32)` if there is a prefix skip it,
 * the convention about prefix it must be separated by underscore from the token like `api_........`
 * - check the `user.expire_time` column, must be empty or in the future
 * - compare the stored user secret by comparing `SHA256(token.substr(32))` with {@link module:lib.timingSafeEqual}
 *
 * @param {RequestContext} context
 * @param {function(err:object, user:object)} callback
 * @memberof module:api/users
 * @method verifyToken
 */
mod.verifyToken = function(context, callback)
{
    const auth = context.auth;
    if (!auth.token) {
        logger.debug("verifyToken:", mod.name, "notoken:", context);
        return callback({ status: 401, message: mod.errInvalidSession });
    }

    // Skip optional prefix
    const pos = auth.token.indexOf("_") + 33;

    mod.get({ login: auth.token.substr(0, pos) }, (err, user) => {
        if (err) return callback(err);

        if (!user) {
            logger.debug("verifyToken:", mod.name, "notfound:", context);
            return callback({ status: 401, message: mod.errInvalidSession });
        }

        if (user.expire_time > 0 && user.expire_time < Date.now()) {
            logger.debug("verifyToken:", mod.name, "expired:", context, user.id, user.name, user.expire_time);
            return callback({ status: 401, message: mod.errInvalidSession });
        }

        const secret = lib.hash(auth.token.substr(pos));

        if (!lib.timingSafeEqual(user.secret, secret)) {
            logger.debug("verifyToken:", mod.name, "invalid:", context, user.id, user.name);
            return callback({ status: 401, message: mod.errInvalidSession });
        }

        context.user = user;

        callback(err, user);
    });
}

/**
 * Creates a cookie session and store .exp in the `user.sessions` property, cleanup expired sessions
 * @param {RequestContext} context
 * @param {object} user - validated user record
 * @memberof module:api/users
 * @method prepareSession
 */
mod.prepareSession = function(context, user)
{
    const session = api.session.create(context, user?.id, user?.secret);
    if (!session) return;

    // This is not atomic on purpose, not going to support simultaneous logins from multiple places at once
    user.sessions = lib.split(user.sessions, { datatype: "int" }).
                        filter(x => x > Date.now());

    user.sessions.push(session.exp);
}

/**
 * Prepare an API token before saving in the database, generates UUIDv4 in place login/secret properties.
 * @param {object} user - user record
 * @param {object} [options]
 * @param {string} [options.prefix] - prefix for the login part
 * @returns {string} token - formatted as `login+secret`
 * @memberof module:api/users
 * @method prepareToken
 * @example
 * api.users.prepareToken(query, { prefix:"test_" })
 * 'test_9f73e6cbcbe2440bb3e304ce1316507b1d1cfdedaf7841a6883c9bbf6cf02593'
 */
mod.prepareToken = function(user, options)
{
    user.login ??= lib.uuid(options?.prefix);

    const secret = lib.uuid();
    user.secret = lib.hash(secret);

    return `${user.login}${secret}`;
}

/**
 * Prepare a MFA code to be sent and saved in `mfa_code` property
 * @param {object} user - user record
 * @param {object} [options]
 * @param {string} [options.method=email]
 * @returns {number} code - generated random code
 * @memberof module:api/users
 * @method prepareMFA
 * @example
 * const { sendmail, api } = required("backendjs");
 *
 * const user = await api.users.get('user@email');
 * const code = api.users.prepareMFA(user);
 * await api.users.aupdate({ login: user.login, mfa_code: user.mfa_code });
 *
 * sendmail.send({ to: user.login, subject: "Verification code", text: `Your verification code ${code}`, lib.log)
 */
mod.prepareMFA = function(user, options)
{
    const code = lib.randomInt(100000, 999999);
    user.mfa_code = `${code},${Date.now() + mod.mfaAge},${options?.method || "email"}`;
    return code;
}

/**
 * Prepare a new TOTP secret to be saved in the user record
 * @param {object} user - user record
 * @returns {object} - same user record with updated topt_secret property
 * @memberof module:api/users
 * @method prepareTOTP
 * @example
 * const user = await api.users.get('user@email')
 * const code = api.users.prepareTOTP(user);
 * await api.users.aupdate({ login: user.login, totp_secret: user.totp_secret });
 */
mod.prepareTOTP = function(user, _options)
{
    user.totp_secret = lib.toBase32(Buffer.from(lib.random().slice(0, 16)));
    return user;
}

/**
 * Login with just the secret, set the user in the context, creates a cookie session and
 * store .exp in the `sessions` column, cleanup expired sessions.
 *
 * Verification code will be enforced if a user has TOPT secret or mfa code saved.
 *
 * In case MFA is wrong or missing the error object will contain a property `code: "MFA"` to signal the UI
 * to deal with it by asking for code or using a separate endpoint to send it.
 * The user record is returned in the callback because it was verified already.
 *
 * @param {RequestContext} context
 * @param {object} context.body - login credentials
 * @param {string} context.body.login - username or email
 * @param {string} context.body.secret - clear text password
 * @param {string} [context.body.code] - optional MFA/TOTP code if enabled
 * @param {function(err:object, user:object)} callback
 * @memberof module:api/users
 * @method login
 * @example
 *
 * api.app.post("/login", (context) => {
 *
 *    api.users.login(context, async (err, user) => {
 *
 *        if (err?.code === "MFA" && user.mfa_code) {
 *            const code = api.users.prepareMFA(user);
 *            await api.users.aupdate({ login: user.login, mfa_code: user.mfa_code });
 *            await sendmail.asend({ to: user.login, subject: "Verification code", text: `Your verification code ${code}`);
 *            err.message += "\nPlease provide the code that was sent to your email";
 *        } else {
 *            err.message += "\nPlease provide code from your auth app";
 *        }
 *        context.reply(err, api.users.cleanup(user));
 *    })
 * })
 */
mod.login = function(context, callback)
{
    const { err, data } = api.validate(context, {
        login: { required: 1 },
        secret: { required: 1 },
        code: {},
    });
    if (err) return lib.tryCall(callback, err);

    mod.checkSecret(data, (err, user) => {
        if (err) return lib.tryCall(callback, err);

        const now = Date.now();

        let totp, mfa;

        if (user.totp_secret) {
            totp = data.code === lib.totp(user.totp_secret);
        }

        if (user.mfa_code) {
            const [code, expires] = lib.split(user.mfa_code);
            mfa = data.code === code && lib.toNumber(expires) > now;
        }

        if (totp === true || mfa === true) {
            logger.debug("login:", mod.name, "mfa:", context, user.id, user.name, totp, mfa);
        } else

        if (totp === false || mfa === false) {
            logger.debug("login:", mod.name, "nomfa:", context, user.id, user.name, totp, mfa);
            return lib.tryCall(callback, { status: 401, message: mod.errInvalidCode, code: "MFA" }, user);
        }

        mod.prepareSession(context, user);

        mod.update({ login: user.login, login_time: now, access_time: now, sessions: user.sessions }, callback);
    });
}

/**
 * Async version of the {@link module:api/users.login} method
 * @param {RequestContext} context
 * @param {object} context.body - login credentials
 * @param {string} context.body.login - username or email
 * @param {string} context.body.secret - clear text password
 * @param {string} [context.body.code] - optional MFA/TOTP code if enabled
 * @returns {{err:object, user:object}}
 * @example
 * api.app.post("/login", async (context) => {
 *
 *     const { err, user } = await api.users.alogin(context);
 *
 *     context.reply(err);
 * });
 * @memberof module:api/users
 * @method alogin
 * @async
 */

mod.alogin = function(context)
{
    return new Promise((resolve, _reject) => {
        mod.login(context, (err, user) => {
            resolve({ err, user });
        });
    });
}

/**
 * Clear session, delete expired sessions
 * Passing `&force=1` in the query url will clear all sessions for a user
 * @param {RequestContext} context
 * @param {function(err:object)} callback
 * @memberof module:api/users
 * @method logout
 */
mod.logout = function(context, callback)
{
    const { user, session } = context;

    if (!user?.id || !session?.id) {
        return lib.tryCall({ status: 401, message: mod.errInvalidSession });
    }

    context.user = null;
    api.session.clear(context);

    // Delete all expired sessions including the current one
    const sessions = lib.isBool(context.query?.force) ? null :
                     lib.split(user.sessions, { datatype: "int" }).
                         filter(x => x !== session.exp && x > Date.now());

    mod.update({ login: user.login, sessions }, (err) => {
        lib.tryCall(callback, err);
    });
}

/**
 * Async version of the {@link module:api/users.logout} method
 * @param {RequestContext} context
 * @returns {Promise}
 * @memberof module:api/users
 * @method alogout
 */

mod.alogout = function(context)
{
    return new Promise((resolve, _reject) => {
        mod.logout(context, (err) => {
            resolve({ err });
        });
    });
}
