/*
 *  Author: Vlad Seryakov vseryakov@gmail.com
 *  backendjs 2018
 */

const fs = require("fs");
const util = require("util");
const crypto = require("node:crypto");
const lib = require(__dirname + '/../lib');
const logger = require(__dirname + '/../logger');
const db = require(__dirname + '/../db');
const api = require(__dirname + '/../api');

/**
 * User management
 *
 * To disable default endpoints
 *
 *    -api-users-cap-disabled 1
 */
const mod = {
    name: "api.users",
    args: [
        { name: "table", descr: "Table to use for users" },
        { name: "err-(.+)", descr: "Error messages for various cases" },
        { name: "cap-(.+)", type: "int", strip: "cap-", descr: "Capability parameters" },
        { name: "max-length", type: "int", descr: "Max login and name length" },
        { name: "users", obj: "users", type: "json", merge: 1, logger: "error", descr: "An object with users" },
        { name: "file", descr: "A JSON file with users" },
    ],
    table: "bk_user",
    maxLength: 140,
    users: {},

    noweb: 0,

    errInvalidUser: "The username is required",
    errInvalidPasswd: "The password is required",
    errInvalidName: "The name is required",
    errInvalidParams: "No username or id provided",
    errInvalidId: "Invalid id provided",
    errInvalidLogin: "No username or password provided",
};
module.exports = mod;

mod.configure = function(options, callback)
{
    this.tables = {
        [this.table]: {
            login: {                                                     // User login/username
                primary: 1,
                max: mod.maxLength,
                keyword: 1,
            },
            id: {                                                        // Autogenerated ID
                type: "uuid",
                pub: 1,
                prefix: "u_",
                unique: 1,
                keyword: 1,
            },
            name: {                                                      // User name
                type: "text",
                pub: 1,
                notempty: 1,
                max: mod.maxLength,
            },
            roles: {                                                      // Permission roles: admin, ....
                type: "list",
                list: 1,
                lower: 1,
                internal: 1,
                keyword: 1,
            },
            flags: {                                                      // Tags/flags
                type: "list",
                list: 1,
                max: mod.maxLength,
                keyword: 1,
            },
            ctime: { type: "now", readonly: 1 },                         // Create time
            mtime: { type: "now" },                                      // Modified time
            secret: { type: "text", max: mod.maxLength, priv: 1 },       // Signature secret or password
            expires: { type: "bigint", internal: 1, priv: 1 },           // Deny access if this value is before current date, ms
            pushkey: { type: "text", priv: 1, max: 4096 },               // Push notifications tokens: [service://]token[@appname]
            passkey: { type: "text", internal: 1, priv: 1, max: 4096 },  // List of registered passkeys in json format
        },
    };

    if (this.file) {
        this.loadFile(this.file, (err) => {
            if (err) return;
            this._watcher = fs.watch(this.file, () => {
                clearTimeout(this._timer);
                this._timer = setTimeout(this.loadFile.bind(this, this.file), lib.randomInt(1000, 5000));
            });
        });
    }

    callback();
}

mod.shutdown = function(options, callback)
{
    clearTimeout(this._timer);
    delete this._timer;
    if (this._watcher?.close) {
        this._watcher.close();
        delete this._watcher;
    }
    lib.tryCall(callback);
}

mod.configureWeb = function(options, callback)
{
    if (this.disabled) return callback();

    // Allow /login to be public without any config if enabled
    api.hooks.add('access', '', /^\/login$/, (req, status, cb) => {
        cb({ status: 200 });
    });

    // Authentication check with signature/session
    api.app.post(/^\/auth$/, (req, res) => {
        if (!req.user?.id) {
            return api.sendReply(res, { status: 417, message: mod.errInvalidLogin, code: "NOLOGIN" });
        }
        api.session.setup(req, () => {
            req.options.cleanup = mod.table;
            req.options.cleanup_strict = 1;
            api.sendJSON(req, null, req.user);
        });
    });

    // Login with just the secret without signature
    api.app.post(/^\/login$/, (req, res) => {
        if (!req.body.login || !req.body.secret) {
            return api.sendReply(res, { status: 417, message: mod.errInvalidLogin, code: "NOLOGIN" });
        }
        // Create internal signature from the login data
        req.signature = api.signature.fromRequest(req, { version: -1, source: "l", login: req.body.login, secret: req.body.secret });
        delete req.body.login;
        delete req.body.secret;

        api.access.authenticate(req, (err) => {
            if (!req.user?.id) {
                return api.sendJSON(req, err || { status: 417, message: mod.errInvalidLogin, code: "NOLOGIN" });
            }
            api.session.setup(req, () => {
                req.options.cleanup = mod.table;
                req.options.cleanup_strict = 1;
                api.sendJSON(req, null, req.user);
            });
        });
    });

    // Clear sessions and access tokens
    api.app.post(/^\/logout$/, (req, res) => {
        api.signature.get(req);
        api.session.clear(req);
        api.csrf.clear(req);
        api.sendJSON(req);
    });

    callback();
}

// Returns a user record by login or id, to make use of a cache add to the config `db-cache-keys-bk_user-id=id`
mod.get = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (typeof query == "string") {
        query = { [lib.isUuid(query) ? "id" : "login"]: query };
    }
    if (query?.login) {
        var user = this.users[query.login];
        if (user) return callback(null, Object.assign({}, user));

        db.get(this.table, query, callback);
    } else
    if (query?.id) {
        for (const p in this.users) {
            if (this.users[p].id == query.id) return callback(null, this.users[p]);
        }
        var opts = { noscan: 1, cacheKeyName: "id", ops: { id: "eq" }, count: 1, first: 1 };
        db.select(this.table, { id: query.id }, opts, (err, row, info) => {
            if (!row) return callback(err);
            // For databases that do not support all columns with indexes(DynamoDB) we have to re-read by the primary key
            if (row.name && row.mtime) return callback(null, row, info);
            db.get(this.table, { login: row.login }, callback);
        });
    } else {
        callback();
    }
}
mod.aget = util.promisify(mod.get.bind(mod));

/**
 * Registers a new user, returns new record in the callback,
 * if `options.isInternal` is true then allow to set all properties
 * `options.internalQuery` can be used to add restricted properties if not in isInternal mode
 * otherwise internal properties will not be added
 */
mod.add = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (!query.login) return lib.tryCall(callback, { status: 400, message: this.errInvalidUser });
    if (!query.secret) return lib.tryCall(callback, { status: 400, message: this.errInvalidPasswd });
    if (!query.name) return lib.tryCall(callback, { status: 400, message: this.errInvalidName });

    options = lib.objClone(options, { result_obj: 1, first: 1 });
    query = Object.assign({}, query);

    this.prepareSecret(query, options, (err) => {
        if (err) return lib.tryCall(callback, err);

        if (!options.isInternal) {
            db.getFilteredColumns(this.table, "internal", { list: 1 }).forEach(x => { delete query[x] })
        }
        Object.assign(query, options?.internalQuery);
        delete query.id;

        db.add(this.table, query, options, (err, row, info) => {
            if (!err) {
                Object.assign(query, row);
            }
            lib.tryCall(callback, err, query, info);
        });
    });
}
mod.aadd = util.promisify(mod.add.bind(mod));

/**
 * Updates an existing user by login or id,
 * if `options.isInternal` is true then allow to update all properties,
 * `options.internalQuery` can be used to add restricted properties if not in isInternal mode
 * returns a new record in the callback
 */
mod.update = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    options = lib.objClone(options, { returning: "*", first: 1 });
    query = Object.assign({}, query);

    this.prepareSecret(query, options, (err) => {
        if (err) return lib.tryCall(callback, err);

        if (!options.isInternal) {
            db.getFilteredColumns(this.table, "internal", { list: 1 }).forEach(x => { delete query[x] });
            if (query.login) delete query.id;
        }
        Object.assign(query, options?.internalQuery);
        if (!query.name) delete query.name;
        if (!this.isUid(query.id)) delete query.id;

        if (query.login) {
            db.update(this.table, query, options, callback);
        } else
        if (query.id) {
            db.select(this.table, { id: query.id }, { cacheKeyName: "id", count: 1, first: 1 }, (err, row) => {
                if (!row) return callback(err, { status: 404, message: this.errInvalidId });

                query.login = row.login;
                db.update(this.table, query, options, callback);
            });
        } else {
            lib.tryCall(callback, { status: 400, message: this.errInvalidParams });
        }
    });
}
mod.aupdate = util.promisify(mod.update.bind(mod));

// Deletes an existing user by login or id, no admin checks, returns the old record in the callback
mod.del = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (typeof query == "string") {
        query = { [this.isUid(query) ? "id" : "login"]: query };
    }
    options = lib.objClone(options, { returning: "old", first: 1 });
    query = Object.assign({}, query, options?.query);

    if (query.login) {
        db.del(this.table, query, options, callback);
    } else
    if (query.id) {
        db.select(this.table, { id: query.id }, { cacheKeyName: "id", count: 1, first: 1 }, (err, row) => {
            if (!row) return callback(err, { status: 404, message: this.errInvalidId });

            query.login = row.login;
            db.del(this.table, query, options, callback);
        });
    } else {
        lib.tryCall(callback, { status: 400, message: this.errInvalidParams });
    }
}
mod.adel = util.promisify(mod.del.bind(mod));

// Returns true of the given id is a valid user uuid
mod.isUid = function(id)
{
    return lib.isUuid(id, this.tables[this.table].id.prefix);
}

// If specified in the options, prepare credentials to be stored in the db, if no error occurred return null, otherwise an error object
mod.prepareSecret = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (!options) options = {};

    if (!query.secret) delete query.secret;

    if (!query.secret) {
        return lib.tryCall(callback);
    }
    lib.prepareSecret(query.secret, (err, secret) => {
        if (!err) query.secret = secret;
        lib.tryCall(callback, err);
    });
}

// Load users from a JSON file, only add or update records
mod.loadFile = function(file, callback)
{
    lib.readFile(file, { json: 1, logger: "error" }, (err, users) => {
        if (!err) {
            for (const p in users) {
                if (users[p].login && users[p].id && users[p].secret && users[p].name) {
                    this.users[users[p].login] = users[p];
                    logger.debug("loadFile:", mod.name, users[p]);
                }
            }
        }
        lib.tryCall(callback, err);
    });
}

