
app-log=info

# connect to node repl to access web process
app-repl-port-web=2090

# enable users module
api-users-table = bk_user

# create ACL named admins with access to our config endpoint
api-acl-add-admins = ^/config

# allow users with admin role to access the admins ACL
api-acl-allow-admin = admins

# allow all authenticated access common endpoints
api-acl-add-* = ^/(profile|logout)

middleware-users-enable = /config/*
middleware-users-login-redirect = /index.html
middleware-users-login-path = /login
middleware-users-logout-path = /logout
middleware-users-profile-path = /profile

# redirect /app endpoints to the main index
middleware-routing-enable = true
middleware-routing-/app = /index.html
middleware-routing-/app/* = /index.html

# parse static body globally
middleware-body-enable = true
middleware-static-enable = true

files-root=var

# Sqlite database
db-pool=sqlite
db-sqlite-pool=var/config

# Local DynamoDB
[roles=dynamodb]
db-pool=dynamodb
db-dynamodb-pool=http://localhost:8181

# Local PostgreSQL-like dbs
[roles=pg]
db-pool=pg
db-pg-pool=default

# Local Elasticsearch
[roles=es]
db-pool=elasticsearch
db-elasticsearch-pool=default

[global]

