
app-log=info
app-log-filter=detect:,gradient:,stats:,outline:,composite:,clip:,text:

# connect to node repl to access web process
app-repl-port-web=2090

# redirect /app endpoints to the main template
middleware-routing-enable = true
middleware-routing-/app = /index.html
middleware-routing-/app/* = /index.html

middleware-body-enable = true
middleware-body-max-size = 10000000

middleware-static-enable = true
