
app-log=info
app-log-filter=detect:,gradient:,stats:,outline:,composite:,clip:,text:

# connect to node repl to access web process
app-repl-port-web=2090

# redirect /app endpoints to the main template
api-routing-path-^/app=/index.html

api-acl-add-public=^/api

api-errlog-codes=4|5

api-query-limit=10000000
