
app-log=info

# connect to node repl to access web process
app-repl-port-web=2090

api-ws-port = 8000

# redirect /app endpoints to the main index
middleware-routing-enable = true
middleware-routing-/app = /index.html
middleware-routing-/app/* = /index.html

# parse static body globally
middleware-body-enable = true
middleware-static-enable = true
middleware-static-etag = true

files-root=var

# Sqlite database
db-pool=sqlite
db-sqlite-pool=var/llms

[global]

