app-log=info

app-log-filter=jobs,gradient:,detect:,stats:,text:,outline:,create:,convert:,getDetails:,getLogos:,composite:,clip:

api-ws-port=8000

app-repl-port-web=2090

api-routing-/app = /index.html
api-routing-/app/* = /index.html

middleware-body-max-size = 10000000
middleware-multipart-max-size = 10000000

middleware-body-enable = true
middleware-multipart-enable = true
middleware-static-enable = true

include @process.env.HOME@/.bkjs.conf

# start worker
jobs-workers=1
jobs-worker-queue=default

# sqlite queue
queue-default = db://?bk-visibilityTimeout=60000

# default db pool
db-pool=sqlite
db-sqlite-pool=var/scraper

files-root=var

