app-log=info

app-log-filter=jobs,gradient:,detect:,stats:,text:,outline:,create:,convert:,getDetails:,getLogos:,composite:,clip:

api-ws-port=8000

app-repl-port-web=2090

api-routing-path-^/app=/index.html

api-acl-add-public=^/api

api-errlog-codes=4|5

api-query-limit=10000000

include @process.env.HOME@/.bkjs.conf

# start worker
jobs-workers=1
jobs-worker-queue=default

# sqlite queue
queue-default = db://?bk-visibilityTimeout=60000

# default db pool
db-pool=sqlite
db-sqlite-pool=var/scraper

# store in global tmp
file-root=var

