//
//  Author: Vlad Seryakov vseryakov@gmail.com
//  backendjs 2018
//

const lib = require(__dirname + '/lib');
const db = require(__dirname + '/db');
const api = require(__dirname + '/api');

const mod = {
    args: [
        { name: "table", descr: "Table to use for user accounts" },
        { name: "salt", descr: "Salt to use for scrambling" },
        { name: "err-(.+)", descr: "Error messages for various cases" },
    ],
    table: "bk_user",
    errInvalidSecret: "Invalid user name or password",
    errInvalidUser: "The username is required",
    errInvalidPasswd: "The password is required",
    errInvalidName: "The name is required",
    errInvalidParams: "No username or id provided",
    errInvalidId: "Invalid id provided",
    errInvalidLogin: "No username or password provided",
};
module.exports = mod;

mod.configure = function(options, callback)
{
    this.tables = {
        [this.table]: {
            login: { primary: 1 },                                      // Account login/username
            id: { type: "uuid", prefix: "u_", unique: 1 },              // Autogenerated ID
            name: { type: "text" },                                     // Account name
            status: { type: "text" },                                   // Status of the account
            secret: { secure: 1 },                                      // Signature secret or scrambled password
            api_secret: { secure: 1 },                                  // Secret for API access token
            type: { type: "list", list: 1, lower: 1, admin: 1 },        // Account roles: admin, ....
            flags: { type: "list", list: 1 },                           // Tags/flags about the account
            rlimits_max: { type: "int", admin: 1 },                     // Burst/max reqs/sec rate allowed for this account, 0 to disable
            rlimits_rate: { type: "int", admin: 1 },                    // Fill/normal reqs/sec rate for this account, 0 to disable
            expires: { type: "bigint", admin: 1, secure: 1 },           // Deny access to the account if this value is before current date, ms
            ctime: { type: "now", readonly: 1 },                        // Create time
            mtime: { type: "now" }
        },
    };

    callback();
}

mod.configureWeb = function(options, callback)
{
    // For health checks
    api.app.all("/ping", function(req, res) {
        api.sendStatus(res, { type: "text/plain" });
    });

    // Authentication check without accounts module
    api.app.all("/auth", function(req, res) {
        if (!req.account || !req.account.id) {
            return api.sendReply(res, { status: 417, message: mod.errInvalidLogin, code: "NOLOGIN" });
        }
        api.handleSessionSignature(req, () => {
            req.options.cleanup = mod.table;
            api.sendJSON(req, null, req.account);
        });
    });

    // Login with just the secret without signature
    api.app.all("/login", function(req, res) {
        if (!req.query.login || !req.query.secret) {
            return api.sendReply(res, { status: 417, message: api.checkErrmsg(req, null, mod.errInvalidLogin), code: "NOLOGIN" });
        }
        // Create internal signature from the login data
        req.signature = api.newSignature(req, "version", -1, "source", "l", "login", req.query.login, "secret", req.query.secret);
        delete req.query.login;
        delete req.query.secret;
        api.checkRequestSignature(req, function(err) {
            if (!req.account || !req.account.id) {
                return api.sendJSON(req, err || { status: 417, message: mod.errInvalidLogin, code: "NOLOGIN" });
            }
            api.handleSessionSignature(req, () => {
                req.options.cleanup = mod.table;
                api.sendJSON(req, null, req.account);
            });
        });
    });

    // Clear sessions and access tokens
    api.app.all("/logout", function(req, res) {
        api.clearSessionSignature(req);
        api.sendJSON(req);
    });

    // Return images by prefix, id and possibly type
    api.app.all(/^\/image\/([a-zA-Z0-9_.:-]+)\/([^/ ]+)\/?([^/ ]+)?$/, function(req, res) {
        var options = api.getOptions(req);
        options.prefix = req.params[0];
        options.type = req.params[2];
        var id = req.params[1];
        // Image extension at the end so it looks like an image path
        if (options.type) {
            const d = options.type.match(/^(.+)\.(png|jpg|jpeg|gif)$/);
            if (d) options.type = d[1], options.ext = d[2];
        } else {
            const d = id.match(/^(.+)\.(png|jpg|jpeg|gif)$/);
            if (d) id = d[1], options.ext = d[2];
        }
        api.sendIcon(req, id, options);
    });

    callback();
}

// If specified in the options, prepare credentials to be stored in the db, if no error occurred return null, otherwise an error object
//  - scramble is used to encrypt the secret with login as HMAC_SHA256 so the db never stores cleartext credentials
//  - bcrypt - if false skip bcrypt, otherwise a number of iterations, 12 is default
mod.prepareSecret = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (!options) options = {};

    if (!query.secret) delete query.secret;

    if (query.login && query.secret && options.scramble) {
        if (this.salt) {
            query.secret = lib.sign(this.salt, query.secret, "sha256");
        } else {
            query.secret = lib.sign(query.secret, query.login, "sha256");

        }
    }

    lib.series([
        function(next) {
            if (!query.secret || options.bcrypt === false) return next();
            if (!api.bcrypt) api.bcrypt = require('bcrypt');
            api.bcrypt.hash(query.secret, lib.toNumber(options.bcrypt, { min: 12, dflt: 12 }), function(err, hash) {
                query.secret = hash;
                next();
            });
        },
        function(next) {
            var hooks = api.findHook('secret', '', query.login);
            if (!hooks.length) return next();
            lib.forEachSeries(hooks, function(hook, next2) {
                hook.callback.call(api, query, options, next2);
            }, next);
        },
    ], callback);
}

// Try to verify a secret against a user record, try all methods
mod.checkSecret = function(user, secret, callback)
{
    if (!user || !user.secret || !user.login || !secret) {
        return callback({ status: 400, message: this.errInvalidSecret });
    }

    // Exact
    if (user.secret == secret) return callback();

    // Scrambled
    var hash = lib.sign(secret, user.login, "sha256");
    if (user.secret == hash) return callback();

    // Salted
    var hash2 = this.salt ? lib.sign(this.salt, secret, "sha256") : "";
    if (user.secret == hash2) return callback();

    // Encrypted
    if (!api.bcrypt) api.bcrypt = require('bcrypt');
    api.bcrypt.compare(secret, user.secret, (err, rc) => {
        if (rc) return callback();

        // Scrambled
        api.bcrypt.compare(hash, user.secret, (err, rc) => {
            if (rc) return callback();

            if (!hash2) return { status: 401, message: this.errInvalidSecret };

            // Salted
            api.bcrypt.compare(hash2, user.secret, (err, rc) => {
                callback(rc ? undefined : { status: 401, message: this.errInvalidSecret });
            });
        });
    });
}

mod.isUid = function(id)
{
    return lib.isUuid(id, this.tables[this.table].id.prefix);
}

// Returns an account record by login or id, to make use of a cache add to the config `db-cache-keys-bk_user-id=id`
mod.get = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (typeof query == "string") {
        query = { [lib.isUuid(query) ? "id" : "login"]: query };
    }
    if (query.login) {
        db.get(this.table, query, callback);
    } else
    if (query.id) {
        var opts = { noscan: 1, cacheKeyName: "id", ops: { id: "eq" }, count: 1, first: 1 };
        db.select(this.table, { id: query.id }, opts, (err, row, info) => {
            if (!row) return callback(err);
            // For databases that do not support all columns with indexes(DynamoDB) we have to re-read by the primary key
            if (row.name && row.mtime) return callback(null, row, info);
            db.get(this.table, { login: row.login }, callback);
        });
    } else {
        callback();
    }
}

// Registers a new account, returns new record in the callback, when options.admin is true then allow to set all properties
// otherwise admin properties will not be added
mod.add = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (!query.login) return lib.tryCall(callback, { status: 400, message: this.errInvalidUser });
    if (!query.secret) return lib.tryCall(callback, { status: 400, message: this.errInvalidPasswd });
    if (!query.name) return lib.tryCall(callback, { status: 400, message: this.errInvalidName });
    options = lib.objClone(options, "result_obj", 1, "first", 1);
    this.prepareSecret(query, options, () => {
        if (!(options.admin || api.checkAccountType(options.account, "admin"))) {
            api.clearQuery(this.table, query, "admin");
        }
        delete query.id;
        db.add(this.table, query, options, (err, row, info) => {
            if (!err) {
                for (const p in row) query[p] = row[p];
            }
            lib.tryCall(callback, err, query, info);
        });
    });
}

// Updates an existing account by login or id, if `options.admin` is true then allow to update all properties, returns a new record in the callback
mod.update = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    options = lib.objClone(options, "returning", "*", "first", 1);
    this.prepareSecret(query, options, () => {
        if (!(options.admin || api.checkAccountType(options.account, "admin"))) {
            api.clearQuery(this.table, query, "admin");
            if (query.login) delete query.id;
        }
        if (!query.name) delete query.name;
        if (!this.isUid(query.id)) delete query.id;
        if (query.login) {
            db.update(this.table, query, options, callback);
        } else
        if (query.id) {
            db.select(this.table, { id: query.id }, { cacheKeyName: "id", count: 1, first: 1 }, (err, row) => {
                if (!row) return callback(err, { status: 404, message: this.errInvalidId });
                query.login = row.login;
                db.update(this.table, query, options, callback);
            });
        } else {
            lib.tryCall(callback, { status: 400, message: this.errInvalidParams });
        }
    });
}

// Deletes an existing account by login or id, no admin checks, returns the old record in the callback
mod.del = function(query, options, callback)
{
    if (typeof options == "function") callback = options, options = null;
    if (typeof query == "string") {
        query = { [this.isUid(query) ? "id" : "login"]: query };
    }
    options = lib.objClone(options, "returning", "old", "first", 1);
    if (query.login) {
        db.del(this.table, query, options, callback);
    } else
    if (query.id) {
        db.select(this.table, { id: query.id }, { cacheKeyName: "id", count: 1, first: 1 }, (err, row) => {
            if (!row) return callback(err, { status: 404, message: this.errInvalidId });
            query.login = row.login;
            db.del(this.table, query, options, callback);
        });
    } else {
        lib.tryCall(callback, { status: 400, message: this.errInvalidParams });
    }
}

