
app-log=info

# connect to node repl to access web process
app-repl-port-web=2090

# redirect /app endpoints to the main template
middleware-routing-enable = true

middleware-routing-/app = /index.html
middleware-routing-/app/* = /index.html

middleware-static-enable = true

