#!/bin/sh
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

[ "$PG_PREFIX" = "" ] && PG_PREFIX=$BKJS_HOME/pg

case "$BKJS_CMD" in

  help|pg-help)
    echo ""
    echo "  pg-init [-home P] [-user postgress] [-db default] - setup new database"
    echo "  pg-run - run local PostgreSQL server installed in $PG_PREFIX"
    echo "  pg-stop - stop local PostgreSQL server"
    echo "  pg-sh - run psql shell"
    ;;

  pg-sh)
    $PG_PREFIX/bin/psql -U postgres -d $(get_arg -db default)
    exit
    ;;

  pg-init)
    user=$(get_arg -user postgres)

    if [ ! -d "$BKJS_HOME/var/pg" ]; then
        $PG_PREFIX/bin/initdb -U $user -D $BKJS_HOME/var/pg
    fi
    $0 pg-run -home $BKJS_HOME
    $PG_PREFIX/bin/createdb -U $user $(get_arg -db default)
    exit
    ;;

  pg-run)
    mkdir -p $BKJS_HOME/var $BKJS_HOME/log

    $PG_PREFIX/bin/pg_ctl -D $BKJS_HOME/var/pg -l $BKJS_HOME/log/pg.log start
    exit
    ;;

  pg-stop)
    pkill -f postgres
    exit
    ;;

  pg-init-monit)
    $0 monit-init -name pg -start "$BKJS_BIN pg-run" -stop "$BKJS_BIN pg-stop"
    exit
    ;;

esac

