#!/bin/bash
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

case "$BKJS_CMD" in

  init-redis)
    ($0 get-redis $(get_all_args))
    ($0 run-redis $(get_all_args))
    if [ "$PLATFORM" = "Linux" ]; then
       sudo $0 init-monit-redis
    fi
    ;;

  get-redis)
    # Install redis server
    case "$PLATFORM" in
     Darwin)
       OS=osx
       REDIS_PREFIX=$BKJS_PREFIX
       ;;
     Linux)
       sudo yum remove -y redis
       sudo yum install -y jemalloc
       REDIS_PREFIX=$BKJS_HOME
       ;;
    esac

    [ -f $REDIS_PREFIX/bin/redis-server ] && exit 0

    ver=$(get_arg -version 5.0.8)
    curl -L -o redis.tgz http://download.redis.io/releases/redis-$ver.tar.gz

    mkdir -p redis $BKJS_HOME/etc
    tar -C redis --strip-components=1 -xzf redis.tgz
    make -C redis install PREFIX=$REDIS_PREFIX
    cp redis/redis.conf $BKJS_HOME/etc
    rm -rf redis redis.tgz
    $SED -e 's|^# syslog-enabled no|syslog-enabled yes|' \
         -e "s|^dir ./|dir $BKJS_HOME/var/|" \
         -e "s|^timeout 0|timeout 3600|" \
         -e "s|^bind|# bind|" \
         -e "s|^protected-mode yes|protected-mode no|" \
         -e "s|^pidfile /var/run/redis.+|pidfile $BKJS_HOME/var/redis.pid|" \
         -e "s|^logfile \"\"|logfile $BKJS_HOME/log/redis.log|" \
         -e "s|^tcp-keepalive .+|tcp-keepalive 60|" \
         -e "s|^maxmemory-policy .+|maxmemory-policy volatile-lru|" \
         -e "s|^# maxmemory-policy .+|maxmemory-policy volatile-lru|" \
         -e 's|^daemonize no|daemonize yes|' \
         $BKJS_HOME/etc/redis.conf
    ;;

  run-redis)
    # Percent from the total memory
    memsize=$(get_arg -memsize)
    [ "$memsize" != "" ] && memmax="$(( ($(free -m|grep Mem:|awk '{print $2}') * $memsize) / 100 ))mb"
    memmax=$(get_arg -memmax $memmax)
    if [ "$memmax" != "" ]; then
       sed -r -i -e "s|^maxmemory .+|maxmemory $memmax|" -e "s|^# maxmemory .+|maxmemory $memmax|" $BKJS_HOME/etc/redis.conf
    fi
    touch $BKJS_HOME/log/redis.log
    redis-server $BKJS_HOME/etc/redis.conf
    slavehost=$(get_arg -slave-host)
    slaveport=$(get_arg -slave-port 6379)
    if [ "$slavehost" != "" ]; then
       redis-cli slaveof $slavehost $slaveport
    fi
    ;;

  stop-redis)
    pkill -f redis-server
    ;;

  run-sentinel)
    redis-sentinel $BKJS_HOME/etc/sentinel.conf
    ;;

  stop-sentinel)
    pkill -f redis-sentinel
    ;;

  init-monit-redis|init-redis-monit)
    # There is no startup script because we rely on the monit to handle processes
    [ "$(whoami)" != "root" ] && echo "Run as root please" && exit 1
    echo 1 > /proc/sys/vm/overcommit_memory
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
    if [ "$(grep -s 'overcommit_memory' /etc/sysctl.conf)" = "" ]; then
       echo 'vm.overcommit_memory=1' >> /etc/sysctl.conf
    fi
    if [ "$(grep -s 'transparent_hugepage' /etc/rc.local)" = "" ]; then
       echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' >> /etc/rc.local
    fi
    find_user
    $ECHO "$BKJS_HOME/log/redis.log {\n  weekly\n  rotate 10\n  copytruncate\n  delaycompress\n  compress\n  notifempty\n  missingok\n}" > /etc/logrotate.d/redis
    $ECHO "check process redis-server with pidfile \"$BKJS_HOME/var/redis.pid\" start program = \"$BKJS_BIN run-redis $(get_all_args)\" as uid $BKJS_USER and gid $BKJS_GROUP stop program = \"$BKJS_BIN stop-redis\" if failed host 127.0.0.1 port 6379 for 2 cycles then restart" > /etc/monit.d/redis.conf
    monit reload
    ;;

  init-monit-sentinel|init-sentinel-monit)
    find_user
    host=$(get_arg -host 127.0.0.1)
    port=$(get_arg -port 6379)
    quorum=$(get_arg -quorum 2)
    name=$(get_arg -name redis)
    dtimeout=$(get_arg -down-timeout 10000)
    ftimeout=$(get_arg -failover-timeout 180000)
    conf=$BKJS_HOME/etc/sentinel.conf
    $ECHO "daemonize yes" > $conf
    $ECHO "syslog-enabled yes" >> $conf
    $ECHO "sentinel monitor $name $host $port $quorum" >> $conf
    $ECHO "sentinel down-after-milliseconds $name $dtimeout" >> $conf
    $ECHO "sentinel failover-timeout $name $ftimeout" >> $conf
    $ECHO "sentinel parallel-syncs $name 1" >> $conf
    $ECHO "dir $BKJS_HOME/var/" >> $conf
    $ECHO "pidfile $BKJS_HOME/var/sentinel.pid" >> $conf
    chown $BKJS_USER $conf

    $ECHO "check process redis-sentinel with pidfile \"$BKJS_HOME/var/sentinel.pid\" start program = \"$BKJS_BIN run-sentinel $(get_all_args)\" as uid $BKJS_USER and gid $BKJS_GROUP stop program = \"$BKJS_BIN stop-sentinel\"" > /etc/monit.d/sentinel.conf
    monit reload
    ;;

  help)
    echo ""
    echo "Redis commands:"
    echo ""
    echo "  get-redis - install Redis server into $REDIS_PREFIX, removes current redis package if installed (Linux only)"
    echo "  init-redis - install and setup Redis server to be run on start and to be monitored (Linux only)"
    echo "  run-redis [-memsize PERCENT] [-memmax SIZE] [-slave-host HOST] - run local Redis server, uses config file $REDIS_CONF"
    echo "  stop-redis - stop local Redis server"
    echo "  run-sentinel - run local Redis Sentinel server, uses config file $REDIS_PREFIX/sentinel.conf"
    echo "  stop-sentinel - stop local Redis Sentinel server"
    echo "  init-sentinel-monit [-host HOST] [-port PORT] - setup Redis Sentinel server to be run on start and to be monitored (Linux only)"
    echo "  init-redis-monit [-memsize PERCENT] [-memmax SIZE] - setup Redis server to be run on start and to be monitored (Linux only)"
    echo ""
    ;;

  *)
    BKJS_UNKNOWN=1
    ;;
esac

