#!/bin/sh

case "$BKJS_CMD" in

  help|alpine-help)
    echo
    echo "  alpine-abuild -name N [-repo REPO] [-image abuild] [-sync S3] [-checksum] [-noexit] - build a package with alpine docker. Place the .apk into -repo folder and -sync to S3 if provided"
    echo "  alpine-run-abuild -name N [-pkgname PKG] [-repo /repo] [-src /src] [-tmp /tmp] - call abuild for given APKBUILD.N file, place in -repo dir and run inside -tmp dir"
    echo "  alpine-prepare-abuild - build Docker image abuild for faster builds"
    echo
    ;;

  alpine-abuild)
    name=$(get_arg -name)
    [ -z "$name" ] && echo "-name is required" && exit 1
    [ ! -f tools/alpine/APKBUILD.$name ] && echo "tools/alpine/APKBUILD.$name is required" && exit 1

    repo=$(get_arg -repo ${BKJS_APKDIR:-$HOME/alpine})
    mkdir -p $repo

    cmd=$(get_arg -cmd)
    [ -z "$cmd" ] && cmd="/src/packages/backendjs/bkjs alpine-run-abuild -name $name -tools /src/tools $(get_all_args "-name -repo -image -cmd -pkgver")"

    # Special case for version from package.json
    pkgver=$(get_flag -pkgver)
    if [ -n "$pkgver" ]; then
        [ "$pkgver" = "1" ] && pkgver=$($BKJS_BIN get-jsval package.json version)
        cmd="$cmd -pkgver $pkgver"
    fi

    volumes="-v $HOME/.abuild:/root/.abuild -v $(pwd):/src -v $repo:/repo"

    image=$(get_arg -image abuild)

    docker run --rm -ti $volumes $image $cmd
    [ "$?" != "0" ] && exit 2

    sync=$(get_arg -sync $BKJS_APKSYNC)
    if [ -d $repo ]; then
        case $sync in
          s3*)
            aws s3 sync $repo/ $sync
            ;;
        esac
    fi
    exit
    ;;

  alpine-run-abuild)
    name=$(get_arg -name)
    [ -z "$name" ] && echo "-name is required" && exit 1
    repo=$(get_arg -repo /repo)
    src=$(get_arg -src /src)
    tmp=$(get_arg -tmp /tmp)
    args=$(get_arg -abuild " -Kk ")

    apk add --update-cache alpine-sdk coreutils cmake sudo

    # generate new abuild key if not set
    if ! grep -sq "^PACKAGER_PRIVKEY=" "$HOME"/.abuild/abuild.conf; then
        USER=alpine abuild-keygen -n -a
    fi
    cp -v "$HOME"/.abuild/*.rsa.pub /etc/apk/keys/

    apk -U upgrade -a

    cp $src/tools/alpine/APKBUILD.$name $tmp/APKBUILD
    cd $tmp

    # Update checksum and exit
    if [ -n "$(get_flag -checksum)" ]; then
        abuild -F checksum
        mv APKBUILD $src/tools/alpine/APKBUILD.$name
        exit
    fi

    # Build with a custom name/version, for a different branch for example
    pkgname=$(get_arg -pkgname)
    if [ -n "$pkgname" ]; then
        $SED "s/^pkgname=.+/pkgname=$pkgname/" APKBUILD
    fi
    pkgver=$(get_arg -pkgver)
    if [ -n "$pkgver" ]; then
        $SED "s/^pkgver=.+/pkgver=$pkgver/" APKBUILD
    fi

    abuild -P $repo -F -r $args

    [ -n "$(get_flag -noexit)" ] && echo "Starting shell.." && /bin/sh -i
    exit
    ;;

  alpine-prepare-abuild)
    docker build --rm -t abuild -f tools/docker/Dockerfile.abuild .
    exit
    ;;

esac
