#!/bin/bash
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

case "$BKJS_CMD" in

  restart)
    [ ! -f /etc/monit.d/$BKJS.conf ] && $0 start
    ;;

  install-bkjs)
    (cd $BKJS_HOME && npm install git+https://github.com/vseryakov/$BKJS_MOD.git $(get_arg -deps))
    ;;

  install)
    [ "$(whoami)" != "root" ] && echo "Run as root please" && exit 1
    args=$(get_all_args)
    find_user
    find_nodebin
    find_bkjsbin
    $0 install-devel $args
    [ "$NODE_BIN" = "" ] && sudo -H -u $BKJS_USER $0 install-node -prefix $BKJS_PREFIX -tools "$(get_arg -tools)"
    [ "$BKJS_BIN" = "" ] && sudo -H -u $BKJS_USER $0 install-bkjs -deps "$(get_arg -deps)" -tools "$(get_arg -tools)"
    (cd $BKJS_HOME/bin && ln -sf ../node_modules/$BKJS_MOD/$BKJS && ln -sf $BKJS bksh)
    $0 init-server $args
    ;;

  install-ec2)
    $0 install -user ec2-user -home /home/ec2-user -prefix /home/ec2-user $(get_all_args "-user -home -prefix")
    $0 init-service
    $0 shell -show-info -db-create-tables
    ;;

  init-server)
    args=$(get_all_args)
    find_user
    find_nodebin
    find_bkjsbin
    echo "Setuping server in $BKJS_HOME for $BKJS_USER/$(get_arg -user), prefix: $BKJS_PREFIX, binaries: $NODE_BIN, $BKJS_BIN... ($args)"

    # Install required packages and utilities
    ($0 init-packages $args)

    ($0 init-hostname $args)
    ($0 init-ssh $args)
    ($0 init-user $args)
    ($0 init-system $args)
    ($0 init-limits $args)
    ($0 init-sysctl $args)
    ($0 init-monit-system $args)
    ($0 init-monit-bkjs $args)
    ($0 init-logrotate $args)
    ($0 init-rsyslog $args)
    ($0 init-home $args)

    # Create global profile
    echo "BKJS_HOME=$BKJS_HOME" > /etc/sysconfig/$BKJS
    domain=$(get_arg -domain)
    [ "$domain" != "" ] && echo "BKJS_DOMAIN=$domain" >> /etc/sysconfig/$BKJS
    [ "$BKJS_USER" != "root" ] && echo "BKJS_USER=$BKJS_USER" >> /etc/sysconfig/$BKJS
    chown -R $BKJS_USER $BKJS_HOME
    ;;

  init-hostname)
    host=$(get_arg -host $BKJS_HOST)
    [ "$host" = "" ] && host=$(uname -n|awk -F. '{print $1}')
    domain=$(get_arg -domain $BKJS_DOMAIN)
    # Set hostname with name and domain
    if [ "$domain" = "" ]; then
       host=$(get_arg -host)
       [ "$host" = "" ] && exit
       domain=$(uname -n|cut -d. -f2-)
    fi
    host=$host.$domain
    [ "$(uname -n)" = "$host" ] && exit
    echo "Configuring hostname $host ..."
    hostname $host
    echo $host > /etc/hostname
    if [ -f /etc/sysconfig/network ]; then
       echo "HOSTNAME=$host" > /tmp/network
       grep -v HOSTNAME /etc/sysconfig/network >> /tmp/network
       mv /tmp/network /etc/sysconfig/network
    fi
    service rsyslog restart
    monit reload
    ;;

  init-user)
    # Add local user
    find_user
    LHOME=/home/$BKJS_USER
    if [ "$(grep -s $BKJS_USER /etc/passwd)" = "" ]; then
       echo "Adding user $BKJS_USER..."
       useradd -g 0 -m $BKJS_USER
       echo "$BKJS_USER ALL = NOPASSWD: ALL" > /etc/sudoers.d/$BKJS
       mkdir -p -m 700 $LHOME/.ssh && chown $BKJS_USER $LHOME/.ssh
       # Copy ssh config if running on Amazon instance
       [ -d /home/ec2-user -a "$BKJS_USER" != "ec2-user" ] && cp /home/ec2-user/.ssh/authorized_keys $LHOME/.ssh && chown $BKJS_USER $LHOME/.ssh/*
    fi

    # Allow path in sudo and skip tty for our user so we can run commands via ssh
    if [ ! -f /etc/sudoers.d/$BKJS ]; then
       echo "Defaults secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:$BKJS_PREFIX/bin:$LHOME/bin:$LHOME/node_modules/.bin" >> /etc/sudoers.d/$BKJS
       echo "Defaults:$BKJS_USER !requiretty" >> /etc/sudoers.d/$BKJS
    fi

    # Aliases and environment
    if [ "$(grep -s '#Bkjs' $LHOME/.bashrc)" = "" ]; then
       echo "Configuring .bashrc..."
       echo '#Bkjs' >> $LHOME/.bashrc
       echo "umask 022" >> $LHOME/.bashrc
       echo "BKJS_HOME=$BKJS_HOME" >> $LHOME/.bashrc
       echo "export PATH=\$PATH:$LHOME/bin:$LHOME/node_modules/.bin" >> $LHOME/.bashrc
       echo 'alias slog="tail -100 /var/log/messages"' >> $LHOME/.bashrc
       echo "alias clog=\"sudo tail -100 /var/log/cron\"" >> $LHOME/.bashrc
       echo "alias mlog=\"tail -100 $BKJS_HOME/log/message.log\"" >> $LHOME/.bashrc
       echo "alias elog=\"tail -100 $BKJS_HOME/log/error.log\"" >> $LHOME/.bashrc
       echo "alias alog=\"tail -100 $BKJS_HOME/log/access.log\"" >> $LHOME/.bashrc
       echo 'alias h="history"' >> $LHOME/.bashrc
       echo 'alias ll="ls -la"' >> $LHOME/.bashrc
       echo 'alias ps="ps augx"' >> $LHOME/.bashrc
       echo 'alias mc="mc -b"' >> $LHOME/.bashrc
       echo 'alias df="df -h"' >> $LHOME/.bashrc
       echo 'alias bkls="bkjs ec2-ls"' >> $LHOME/.bashrc
       echo 'bcp() { socat readline,history=$HOME/.socat tcp4:localhost:$1; }' >> $LHOME/.bashrc
       echo 'ec2ssh() { ssh -i ~/.ssh/$2.pem -l ec2-user $1 $3; }' >> $LHOME/.bashrc
       echo 'ec2scp() { scp -r -i ~/.ssh/$3.pem $1 ec2-user@$2; }' >> $LHOME/.bashrc
       echo 'bkssh() { bkjs ec2-ssh -tag "$1" -index "$2" -cmd "$3" -skip-tag dev,staging; }' >> $LHOME/.bashrc
       echo 'bkstop() { bkjs ec2-ssh -tag ${1-api} -index "$2" -cmd "bkjs stop-${3-api}" -skip-tag dev,staging; }' >> $LHOME/.bashrc
       echo 'bksync() { (cd $HOME/node_modules/$1 && bkjs sync -host $(bkjs ec2-host -tag ${2-api} -skip-tag dev,staging)); }' >> $LHOME/.bashrc
       echo 'bkw() { bkssh ${1-api} "" "w"; }' >> $LHOME/.bashrc
       echo 'bkami() { bkjs create-ami && bkjs create-launch-template-version; }' >> $LHOME/.bashrc
       echo "PROMPT_COMMAND='printf \"\\033]0;\$(cat \$HOME/var/bkjs.tag)\\007\"'" >> $LHOME/.bashrc
       echo '[ ! -s ~/var/bkjs.tag ] && bkjs ec2-tag > ~/var/bkjs.tag' >> $LHOME/.bash_profile
       echo '[ -s ~/var/bkjs.tag ] && export PS1=$(cat ~/var/bkjs.tag)' >> $LHOME/.bash_profile
    fi
    echo "package-lock=false" > $HOME/.npmrc
    ;;

  init-home)
    # Create required directories
    find_user
    mkdir -p $BKJS_HOME/node_modules $BKJS_HOME/bin $BKJS_HOME/log $BKJS_HOME/etc $BKJS_HOME/var
    if [ "$BKJS_USER" != "root" -a ! -f $BKJS_HOME/etc/config ]; then
       echo "Creating default $BKJS config ..."
       $ECHO "uid=$BKJS_USER\nforce-uid=1" > $BKJS_HOME/etc/config
    fi
    chown -R $BKJS_USER $BKJS_HOME
    ;;

  init-ssh)
    # Allow only pubkey auth
    [ "$(grep -s '#Bkjs' /etc/ssh/sshd_config)" != "" ] && exit
    echo "Configuring ssh..."
    egrep -v '^(#Bkjs|PasswordAuth|GSSAPIAuth|MaxAuth|MaxSess|ClientAlive|PermitRootLogin)' /etc/ssh/sshd_config > /tmp/sshd_config
    echo "" >> /tmp/sshd_config
    echo "#Bkjs config" >> /tmp/sshd_config
    echo "PasswordAuthentication no" >> /tmp/sshd_config
    echo "GSSAPIAuthentication no" >> /tmp/sshd_config
    echo "MaxAuthTries 10" >> /tmp/sshd_config
    echo "MaxSessions 10" >> /tmp/sshd_config
    echo "ClientAliveInterval 15" >> /tmp/sshd_config
    echo "ClientAliveCountMax 5" >> /tmp/sshd_config
    echo "PermitRootLogin no" >> /tmp/sshd_config
    mv /tmp/sshd_config /etc/ssh
    chmod 600 /etc/ssh/sshd_config
    service sshd restart
    ;;

  init-logrotate)
    # Setup logrotate for backend log files
    if [ "$(grep -s '#Bkjs' /etc/logrotate.d/syslog)" = "" ]; then
       echo "Configuring logrotate..."
       echo "#Bkjs" > /etc/logrotate.d/syslog
       echo "/var/log/cron /var/log/messages {" >> /etc/logrotate.d/syslog
       echo " missingok" >> /etc/logrotate.d/syslog
       echo " daily" >> /etc/logrotate.d/syslog
       echo " rotate 30" >> /etc/logrotate.d/$BKJS
       echo " sharedscripts" >> /etc/logrotate.d/syslog
       echo " postrotate" >> /etc/logrotate.d/syslog
       echo "  /usr/bin/killall -q -HUP rsyslogd" >> /etc/logrotate.d/syslog
       echo " endscript" >> /etc/logrotate.d/syslog
       echo "}" >> /etc/logrotate.d/syslog
    fi
    if [ "$(grep -s "#Bkjs $BKJS_HOME" /etc/logrotate.d/$BKJS)" = "" ]; then
       echo "Configuring logrotate.d/$BKJS..."
       echo "#Bkjs $BKJS_HOME" > /etc/logrotate.d/$BKJS
       echo "$BKJS_HOME/log/message.log $BKJS_HOME/log/access.log {" >> /etc/logrotate.d/$BKJS
       echo " missingok" >> /etc/logrotate.d/$BKJS
       echo " daily" >> /etc/logrotate.d/$BKJS
       echo " rotate 30" >> /etc/logrotate.d/$BKJS
       echo " sharedscripts" >> /etc/logrotate.d/$BKJS
       echo " postrotate" >> /etc/logrotate.d/$BKJS
       echo "  /usr/bin/killall -q -HUP rsyslogd" >> /etc/logrotate.d/$BKJS
       echo " endscript" >> /etc/logrotate.d/$BKJS
       echo "}" >> /etc/logrotate.d/$BKJS
    fi
    ;;

  init-rsyslog)
    # Setup syslog config for backend logging
    find_user
    if [ "$(grep -s '#Bkjs' /etc/rsyslog.conf)" = "" ]; then
       echo "Configuring rsyslog..."
       echo "#Bkjs" > /etc/rsyslog.conf
       case "$OS_TYPE" in
        amazon2)
          echo '$ModLoad imjournal' >> /etc/rsyslog.conf
          ;;

        *)
          echo '$ModLoad imklog' >> /etc/rsyslog.conf
          ;;
       esac
       echo '$ModLoad imuxsock' >> /etc/rsyslog.conf
       echo '$ModLoad imudp' >> /etc/rsyslog.conf
       echo '$UDPServerAddress 127.0.0.1' >> /etc/rsyslog.conf
       echo '$UDPServerRun 514' >> /etc/rsyslog.conf
       echo '$MaxMessageSize 64k' >> /etc/rsyslog.conf
       echo '$SystemLogRateLimitInterval 1' >> /etc/rsyslog.conf
       echo '$SystemLogRateLimitInterval 1' >> /etc/rsyslog.conf
       echo '$SystemLogRateLimitBurst 10000' >> /etc/rsyslog.conf
       echo '$ActionFileDefaultTemplate RSYSLOG_FileFormat' >> /etc/rsyslog.conf
       case "$OS_TYPE" in
        amazon2)
          echo '$OmitLocalLogging on' >> /etc/rsyslog.conf
          echo '$IMJournalStateFile imjournal.state' >> /etc/rsyslog.conf
          echo '*.emerg :omusrmsg:*' >> /etc/rsyslog.conf
          ;;

        *)
          echo 'kern.*,*.emerg /dev/console' >> /etc/rsyslog.conf
          ;;
       esac
       echo '$IncludeConfig /etc/rsyslog.d/*.conf' >> /etc/rsyslog.conf
       echo 'cron.* /var/log/cron' >> /etc/rsyslog.conf
       echo 'local7.* /var/log/boot.log' >> /etc/rsyslog.conf
       echo "\$FileOwner $BKJS_USER" >> /etc/rsyslog.conf
       echo '*.info;cron.none,local0.none,local5.none /var/log/messages' >> /etc/rsyslog.conf
       rm -rf /var/log/maillog* /var/log/secure* /var/log/spooler*
       touch /var/log/messages
       chown -R $BKJS_USER /var/log/messages
       service rsyslog restart
    fi
    if [ "$(grep -s "#Bkjs $BKJS_HOME" /etc/rsyslog.d/$BKJS.conf)" = "" ]; then
       echo "Configuring rsyslog.d/$BKJS ..."
       echo "#Bkjs $BKJS_HOME" > /etc/rsyslog.d/$BKJS.conf
       echo "\$FileOwner $BKJS_USER" >> /etc/rsyslog.d/$BKJS.conf
       echo "local0.* $BKJS_HOME/log/message.log" >> /etc/rsyslog.d/$BKJS.conf
       echo "local5.* $BKJS_HOME/log/access.log" >> /etc/rsyslog.d/$BKJS.conf
       mkdir -p $BKJS_HOME/log
       chown -R $BKJS_USER $BKJS_HOME/log
       service rsyslog restart
    fi
    ;;

  init-system)
    # Disable SELinux
    if [ -f /etc/selinux/config ]; then
        sed -i 's/SELINUX=(enforcing|permissive)/SELINUX=disabled/' /etc/selinux/config
    fi

    # Disable internal firewall
    chkconfig iptables off
    service iptables stop

    # Make sure monit is running all the time
    echo "set logfile syslog" > /etc/monit.d/logging
    sed -i 's|daemon $prog|ulimit -n 512000\n\tdaemon $prog|' /etc/init.d/monit
    chkconfig monit on
    service monit restart

    # Allow sudo use local binaries
    sed -i 's/requiretty/!requiretty/' /etc/sudoers
    ;;

  init-limits)
    # File handles and coredumps for debugging
    conf=/etc/security/limits.d/90-$BKJS.conf
    [ -s $conf ] && exit
    echo "Configuring limits..."
    echo '* soft core unlimited' > $conf
    echo '* hard core unlimited' >> $conf
    echo '* soft nofile 512000' >> $conf
    echo '* hard nofile 512000' >> $conf
    echo 'root soft nofile 512000' >> $conf
    echo 'root hard nofile 512000' >> $conf
    echo '* soft memlock unlimited' >> $conf
    echo '* hard memlock unlimited' >> $conf
    echo 'root soft memlock unlimited' >> $conf
    echo 'root hard memlock unlimited' >> $conf
    echo '* soft as unlimited' >> $conf
    echo '* hard as unlimited' >> $conf
    echo 'root soft as unlimited' >> $conf
    echo 'root hard as unlimited' >> $conf
    ;;

  init-sysctl)
    # System tuning
    conf=/etc/sysctl.d/90-$BKJS.conf
    [ -s $conf ] && exit
    echo "Configuring sysctl..."
    echo 'fs.file-max=512000' > $conf
    echo 'kernel.core_uses_pid=0' >> $conf
    echo 'vm.max_map_count=262144' >> $conf
    echo 'vm.min_free_kbytes=65536' >> $conf
    echo 'net.core.somaxconn=16384' >> $conf
    echo 'net.core.netdev_max_backlog=16384' >> $conf
    echo 'net.core.rmem_max=8388608' >> $conf
    echo 'net.core.wmem_max=8388608' >> $conf
    echo 'net.ipv4.tcp_rfc1337=1' >> $conf
    echo 'net.ipv4.ip_local_port_range=1024 65000' >> $conf
    echo 'net.ipv4.tcp_max_tw_buckets=400000' >> $conf
    echo 'net.ipv4.tcp_tw_reuse=1' >> $conf
    echo 'net.ipv4.tcp_fin_timeout=15' >> $conf
    echo 'net.ipv4.tcp_keepalive_intvl=15' >> $conf
    echo 'net.ipv4.tcp_slow_start_after_idle=0' >> $conf
    echo 'net.ipv4.tcp_max_orphans=262144' >> $conf
    echo 'net.ipv4.tcp_max_syn_backlog=16384' >> $conf
    echo 'net.ipv4.tcp_no_metrics_save=1' >> $conf
    echo 'net.ipv4.tcp_syn_retries=2' >> $conf
    echo 'net.ipv4.tcp_synack_retries=2' >> $conf
    echo 'net.ipv4.tcp_rmem=8192 256000 8388608' >> $conf
    echo 'net.ipv4.tcp_wmem=4096 256000 8388608' >> $conf
    echo 'net.ipv4.tcp_challenge_ack_limit = 999999999' >> $conf
    sysctl -p $conf
    ;;

  init-postfix)
    # Setup postfix with origin domain name
    [ "$(grep -s '#Bkjs' /etc/postfix/main.cf)" != "" ] && exit
    yum -y -q remove sendmail
    yum -y -q install postfix
    echo "Configuring postfix..."
    echo '#Bkjs' > /tmp/main.cf
    echo 'myorigin = $mydomain' >> /tmp/main.cf
    egrep -v '^(#Bkjs|myorigin)' /etc/postfix/main.cf >> /tmp/main.cf
    mv /tmp/main.cf /etc/postfix
    chkconfig postfix on
    postfix start
    ;;

  init-dns)
    # DNS cache
    [ "$(grep -s '#Bkjs' /etc/dnsmasq.conf)" != "" ] && exit
    yum -y -q install dnsmasq
    echo "#Bkjs" > /etc/dnsmasq.conf
    echo "domain-needed" >> /etc/dnsmasq.conf
    echo "bogus-priv" >> /etc/dnsmasq.conf
    echo "no-resolv" >> /etc/dnsmasq.conf
    echo "no-poll" >> /etc/dnsmasq.conf
    grep nameserver /etc/resolv.conf |grep -v 127|sed 's/nameserver /server=/' >> /etc/dnsmasq.conf
    echo "server=8.8.8.8" >> /etc/dnsmasq.conf
    echo "server=8.8.4.4" >> /etc/dnsmasq.conf
    echo "listen-address=127.0.0.1" >> /etc/dnsmasq.conf
    echo "no-dhcp-interface=" >> /etc/dnsmasq.conf
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
    echo "search $BKJS_DNS" >> /etc/resolv.conf
    chkconfig dnsmasq on
    service dnsmasq restart
    ;;

  init-adhoc)
    find_bkjsbin
    # Duplicate messages to the console for easier access
    echo '*.info /dev/console' > /etc/rsyslog.d/console.conf
    truncate -c -s 0 /var/log/messages $BKJS_HOME/log/message.log $BKJS_HOME/log/error.log
    service rsyslog restart
    # Support for shutdown as normal user for instances
    chmod u+s /sbin/reboot
    # Make sure instances are not running indefinitely
    cron=$(get_arg -cron "*/30 * * * *")
    echo 'MAILTO=""' > /etc/cron.d/$BKJS-adhoc
    echo "$cron root $BKJS_BIN check-adhoc" >> /etc/cron.d/$BKJS-adhoc
    ;;

  init-service)
    # Install service for a script or bkjs service
    find_user
    find_bkjsbin
    path=$(get_arg -path $BKJS_BIN)
    [ "$path" = "" ] && echo "no $BKJS path specified or detected" && exit 1
    service=$(basename $path | awk -F. '{print $1}')
    echo "Init service $service with $path"
    ln -sf $path /etc/init.d/$service
    chkconfig $service on
    server=$(get_arg -server)
    if [ "$server" != "" ]; then
       echo "BKJS_SERVER=$server" > /tmp/profile
       grep -vs BKJS_SERVER $BKJS_HOME/etc/profile >> /tmp/profile
       mv /tmp/profile $BKJS_HOME/etc
       chown $BKJS_USER $BKJS_HOME/etc/profile
    fi
    # Execute a command if given
    cmd=$(get_arg -cmd)
    [ "$cmd" != "" ] && service $service $cmd
    ;;

  stop-service)
    find_bkjsbin
    path=$(get_arg -path $BKJS_BIN)
    [ "$path" = "" ] && echo "no $BKJS path specified or detected" && exit 1
    service=$(basename $path | awk -F. '{print $1}')
    echo "Stopping service $service with $path"
    chkconfig $service off
    $0 stop-monit-$service
    $0 stop
    ;;

  init-mfa)
    [ "$(whoami)" != "root" ] && echo "Run as root please" && exit 1
    yum install google-authenticator –y
    if [ "$(egrep -s 'pam_google_authenticator' /etc/pam.d/sshd)" = "" ]; then
       sed -i -r 's|^auth[ \t]+substack[ \t]+password-auth|auth required pam_google_authenticator.so\n#auth substack password-auth|' /etc/pam.d/sshd
    fi
    if [ "$(egrep -s 'pam_google_authenticator' /etc/pam.d/system-auth)" = "" ]; then
       sed -i -r 's|^auth[ \t]+sufficient[ \t]+pam_unix.so nullok try_first_pass|auth requisite pam_unix.so nullok try_first_pass\nauth sufficient pam_google_authenticator.so|' /etc/pam.d/system-auth
    fi
    echo >> /etc/ssh/sshd_config
    if [ "$(egrep -s '^ChallengeResponseAuthentication yes' /etc/ssh/sshd_config)" = "" ]; then
       sed -i -r 's|^ChallengeResponseAuthentication|#ChallengeResponseAuthentication|' /etc/ssh/sshd_config
       echo 'ChallengeResponseAuthentication yes' >> /etc/ssh/sshd_config
    fi
    if [ "$(egrep -s '^AuthenticationMethods publickey,keyboard-interactive' /etc/ssh/sshd_config)" = "" ]; then
       sed -i -r 's|^AuthenticationMethods|#AuthenticationMethods|' /etc/ssh/sshd_config
       echo 'AuthenticationMethods publickey,keyboard-interactive' >> /etc/ssh/sshd_config
    fi
    su $(get_arg -user ec2-user) -c "google-authenticator -d -t -f -r 2 -R 30"
    ;;

  init-logwatcher)
    find_user
    find_bkjsbin
    cron=$(get_arg -cron "*/$(get_arg -interval 5) * * * *")
    echo 'MAILTO=""' > /etc/cron.d/$BKJS-logwatcher
    echo "$cron $BKJS_USER $BKJS_BIN logwatcher" >> /etc/cron.d/$BKJS-logwatcher
    ;;

  init-packages)
    # Install required runtime packages
    packages="ntp rsync wget socat mc nano man telnet monit"

    yum -y -q update

    # Linux distro specific actions
    case "$OS_TYPE" in
      amazon)
        yum-config-manager --enable epel
        yum -y remove java-1.7.0-openjdk
        packages="$packages java-1.8.0"
        ;;

      amazon2)
        amazon-linux-extras enable epel
        packages="$packages java-1.8.0-openjdk"
        yum clean metadata
        yum install epel-release
        ;;
    esac
    sleep 10
    yum -y -q install $packages
    ;;

  help)
    echo ""
    echo "Instance setup commands:"
    echo ""
    echo "  install-bkjs [-deps PKGS] - install the $BKJS_MOD from the github using npm, build dependencies are passed in -deps"
    echo "  install - [-user USER] [-home HOME] [-prefix $PREFIX] [-doman DOMAIN] [-host HOST] - make server setup and install all pakages including node and the $BKJS_MOD"
    echo "  install-ec2 - setup server on EC2 instance in the ec2-user home"
    echo "  init-server [-user USER] [-home HOME] [-prefix $PREFIX] [-doman DOMAIN] [-host HOST] - initialize the backend environment, setup the Linux server with packages and change system config files for production use (Amazon AMI, CentOS)"
    echo "  init-hostname [-host HOST] [-domain DOMAIN] - set the hostname"
    echo "  init-user [-user NAME] - create a new user for the backend"
    echo "  init-ssh - setup SSH permissions, allow only public key auth"
    echo "  init-logrotate - setup logrotate for the backend log files"
    echo "  init-rsyslog - setup rsyslog to use for the backend logging, access log and backend log"
    echo "  init-system - setup system wide parameters, permissions"
    echo "  init-limits - setup ulimits"
    echo "  init-sysctl - setup sysctl parameters"
    echo "  init-postfix - [-domain DOMAIN] install and configure postfix for the domain"
    echo "  init-dns - install and setup dnsmasq for local cahching DNS server"
    echo "  init-adhoc - configure for running temporary ad-hoc instances"
    echo "  init-packages - install required packges and updates"
    echo "  init-home - setup backend home with required folders"
    echo "  init-mfa [-user ec2-user] - initialize EC2 instance with multi-factor authentication using Google authenticator"
    echo "  init-logwatcher [-interval MINS] [-cron CRON] - creates a crontab file in /etc/cron.d to periodically run the log watcher, -cron can specify full cron time spec"
    echo "  init-service [-server NAME] - create $BKJS service to be run on server startup, i.e. makes symlink /etc/init.d/$BKJS after which regular 'service' command can be used to manage the $BKJS service"
    echo "  stop-service - stop $BKJS service from starting on startup"
    ;;

  *)
    BKJS_UNKNOWN=1
    ;;
esac

