#!/bin/sh
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

case "$BKJS_CMD" in

  elasticsearch-get)
    [ "$ELASTICSEARCH_PREFIX" = "" ] && ELASTICSEARCH_PREFIX=$BKJS_HOME/elasticsearch
    [ "$(get_flag -force)" != "" -a "$ELASTICSEARCH_PREFIX" != "" ] && rm -rf $ELASTICSEARCH_PREFIX
    if [ ! -d $ELASTICSEARCH_PREFIX ]; then
        mkdir -p $ELASTICSEARCH_PREFIX
        platform=$(echo $PLATFORM | tr [:upper:] [:lower:])
        case $OS_ARCH in
          arm64)
            platform="$platform-aarch64"
            ;;
          *)
            platform="$platform-x86_64"
            ;;
        esac
        ver=$(get_arg -vesion 8.8.1)
        curl -L -o es.tgz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ver-$platform.tar.gz
        tar -C $ELASTICSEARCH_PREFIX --strip-components=1 -xzf es.tgz
        rm -rf es.tgz
        cd $ELASTICSEARCH_PREFIX
        echo "node.roles: [master,data]" >> config/elasticsearch.yml
        echo "path.data: $BKJS_HOME/var" >> config/elasticsearch.yml
        echo "path.logs: $BKJS_HOME/log" >> config/elasticsearch.yml
        echo "action.destructive_requires_name: true" >> config/elasticsearch.yml
        echo 'xpack.security.enabled: false' >> config/elasticsearch.yml
        if match $OS_TYPE amazon; then
            echo 'network.host: ["_ec2_","_local_"]' >> config/elasticsearch.yml
            echo 'discovery.seed_providers: ec2' >> config/elasticsearch.yml
            echo 'cloud.node.auto_attributes: true' >> config/elasticsearch.yml
            echo 'cluster.routing.allocation.awareness.attributes: aws_availability_zone' >> config/elasticsearch.yml
            bin/elasticsearch-plugin install discovery-ec2 -b
        fi
        echo "-Dlog4j2.formatMsgNoLookups=true" >> config/jvm.options
    fi
    exit
    ;;

  elasticsearch-init)
    ($0 elasticsearch-get $(get_all_args))
    ($0 elasticsearch-run $(get_all_args))
    if [ "$PLATFORM" = "Linux" ]; then
       sudo $0 elasticsearch-init-monit $(get_all_args)
    fi
    exit
    ;;

  elasticsearch-get-nodetype)
    [ "$ELASTICSEARCH_PREFIX" = "" ] && ELASTICSEARCH_PREFIX=$BKJS_HOME/elasticsearch
    roles=$(grep "node.roles:" $ELASTICSEARCH_PREFIX/config/elasticsearch.yml|awk -F: '{print $2}'|sed 's/[^a-z]//g')
    case "$roles" in
    masterdata|datamaster)
      echo node
      ;;
    data)
      echo data
      ;;
    master)
      echo master
      ;;
    "")
      echo client
      ;;
    esac
    exit
    ;;

  elasticsearch-run)
    [ "$ELASTICSEARCH_PREFIX" = "" ] && ELASTICSEARCH_PREFIX=$BKJS_HOME/elasticsearch
    # Percent from the total memory
    memsize=$(get_arg -memsize)
    [ -n "$memsize" ] && memmax="$(( ($(free -m|grep Mem:|awk '{print $2}') * $memsize) / 100 ))m"
    memmax=$(get_arg -memmax $memmax)
    if [ -n "$memmax" ]; then
       $SED "s/^-Xms.+/-Xms$memmax/" $ELASTICSEARCH_PREFIX/config/jvm.options
       $SED "s/^-Xmx.+/-Xmx$memmax/" $ELASTICSEARCH_PREFIX/config/jvm.options
       mkdir -p $ELASTICSEARCH_PREFIX/config/jvm.options.d/
       echo "-Xms$memmax" > $ELASTICSEARCH_PREFIX/config/jvm.options.d/bkjs.options
       echo "-Xmx$memmax" >> $ELASTICSEARCH_PREFIX/config/jvm.options.d/bkjs.options
    fi
    case "$(get_arg -nodetype)" in
    node)
      $SED -e "s/^node.roles.+$/node.roles: [master,data]/" $ELASTICSEARCH_PREFIX/config/elasticsearch.yml
      ;;
    master)
      $SED -e "s/^node.roles.+$/node.roles: [master]/" $ELASTICSEARCH_PREFIX/config/elasticsearch.yml
      ;;
    data)
      $SED -e "s/^node.roles.+$/node.roles: [data]/" $ELASTICSEARCH_PREFIX/config/elasticsearch.yml
      ;;
    client)
      $SED -e "s/^node.roles.+$/node.roles: []/" $ELASTICSEARCH_PREFIX/config/elasticsearch.yml
      ;;
    any)
      $SED -e "s/^node.roles.+$/node.roles: [master,data,ingest,ml,transform]/" $ELASTICSEARCH_PREFIX/config/elasticsearch.yml
      ;;
    esac
    $ELASTICSEARCH_PREFIX/bin/elasticsearch -p $BKJS_HOME/var/elasticsearch.pid -d >>$BKJS_HOME/log/message.log 2>&1
    exit
    ;;

  elasticsearch-stop)
    pkill -f org.elasticsearch
    exit
    ;;

  elasticsearch-restart)
    pkill -f org.elasticsearch
    sleep 1
    pkill -f -9 org.elasticsearch
    $0 elasticsearch-run $(get_all_args)
    exit
    ;;

  elasticsearch-reset)
    pkill -f org.elasticsearch
    rm -rf $BKJS_HOME/var/nodes
    rm -f $BKJS_HOME/log/elasticsearch*
    $0 elasticsearch-run
    exit
    ;;

  elasticsearch-configure)
    host=$(get_arg -host localhost)
    curl -XPUT -H 'Content-Type: application/json' -d '{"persistent":{"script.max_compilations_rate":"1000/1m"}}' http://$host:9200/_cluster/settings
    exit
    ;;

  elasticsearch-stop-replication)
    host=$(get_arg -host localhost)
    curl -XPUT -H 'Content-Type: application/json' -d '{"persistent":{"cluster.routing.allocation.enable":"primaries"}}' http://$host:9200/_cluster/settings
    exit
    ;;

  elasticsearch-start-replication)
    host=$(get_arg -host localhost)
    curl -XPUT -H 'Content-Type: application/json' -d '{"persistent":{"cluster.routing.allocation.enable":null}}' http://$host:9200/_cluster/settings
    exit
    ;;

  elasticsearch-set-disk-watermark)
    host=$(get_arg -host localhost)
    high=$(get_arg -high 95)
    low=$(get_arg -low 95)
    flood=$(get_arg -flood 95)
    curl -XPUT -H 'Content-Type: application/json' -d "{\"transient\":{\"cluster.routing.allocation.disk.watermark.flood_stage\":\"$flood%\",\"cluster.routing.allocation.disk.watermark.high\":\"$high%\",\"cluster.routing.allocation.disk.watermark.low\":\"$low%\"}}" http://$host:9200/_cluster/settings
    exit
    ;;

  elasticsearch-reindex)
    host=$(get_arg -host localhost)
    index=$(get_arg -index)
    dest=$(get_arg -dest $index)
    remote=$(get_arg -remote $host)
    d='{ "source": { "index": "'$index'", "remote": { "host": "http://'$remote':9200" } }, "dest": {"index": "'$dest'" } }'
    curl -XPOST -H 'Content-Type:application/json' -d "'$d'" "http://$host:9200/_reindex?wait_for_completion=false"
    exit
    ;;

  elasticsearch-upgrade-node)
    host=$(get_arg -host localhost)
    memsize=$(get_arg -memsize 50)
    nodetype=$($0 get_arg -nodetype)
    $0 elasticsearch-stop-replication -host $host
    $0 elasticsearch-stop
    $0 elasticsearch-get -force
    if [ -f /etc/monit.d/elasticsearch.conf ]; then
        sudo monit reload
    else
        $0 elasticsearch-run -nodetype "$nodetype" -memsize $memsize
    fi
    $0 elasticsearch-start-replication -host $host
    exit
    ;;

  elasticsearch-exclude-node)
    host=$(get_arg -host localhost)
    ip=$(get_arg -ip $(get_local_ip))
    [ "$ip" = "." ] && ip=""
    curl -XPUT -H 'Content-Type: application/json' -d "{\"transient\":{\"cluster.routing.allocation.exclude._ip\":\"$ip\"}}" http://$host:9200/_cluster/settings
    exit
    ;;

  elasticsearch-init-monit)
    echo "check process elasticsearch with pidfile \"$BKJS_HOME/var/elasticsearch.pid\" start program = \"$BKJS_BIN elasticsearch-run $(get_all_args)\" as uid $BKJS_USER stop program = \"$BKJS_BIN elasticsearch-stop\" if failed url http://127.0.0.1:9200/ with timeout 15 seconds for 2 cycles then restart" > /etc/monit.d/elasticsearch.conf
    echo "check file elasticsearch-log with path $BKJS_HOME/log/elasticsearch.log if match 'java.lang.OutOfMemoryError' then exec \"$BKJS_BIN restart-elasticsearch $(get_all_args)\"" >> /etc/monit.d/elasticsearch.conf
    exit
    ;;

  elasticsearch-init-monit-health)
    host=$(get_arg -host elasticsearch)
    echo "check host elasticsearch-health with address $host if failed url http://$host:9200/_cluster/health and content = 'green' with timeout 60 seconds for 2 cycles then alert" > /etc/monit.d/elasticsearch-health.conf
    exit
    ;;

  help)
    echo ""
    echo "  elasticsearch-get [-force] - install local ElasticSearch server in $BKJS_HOME/elasticsearch"
    echo "  elasticsearch-init - download and install local ElasticSearch, start the server, configure monit"
    echo "  elasticsearch-run [-memsize PERCENT] [-memmax SIZE] [-nodetype TYPE] - run local ElasticSearch server installed in $BKJS_HOME/elasticsearch, -memmax is max heap size, -memsize is the percent of the total memory to use, -nodetype can be node,master,data,client"
    echo "  elasticsearch-stop - stop local ElasticSearch server"
    echo "  elasticsearch-reset - remove local ElasticSearch database and restart the server"
    echo "  elasticsearch-configure - configure ElasticSearch common parameters for scalability"
    echo "  elasticsearch-init-monit [-memsize PERCENT] [-memmax SIZE] [-nodetype TYPE] - setup monit to keep elasticsearch service running"
    echo "  elasticsearch-exclude-node [-host HOST] [-ip IP] - disable a node by IP address"
    echo "  elasticsearch-reindex -index INDEX [-dest INDEX] [-host HOST] [-remote HOST] - reindex an index from remote host"
    ;;
esac

