#!/bin/sh
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

case "$BKJS_CMD" in

  deps)
    find_nodebin
    [ "$NPM_BIN" = "" -a ! -f $BKJS_PREFIX/bin/npm ] && NPM_BIN=$(which npm 2>/dev/null)
    [ "$NPM_BIN" = "" ] && NPM_BIN=$BKJS_PREFIX/bin/npm
    cmd=install
    [ ! -z "$(get_flag -update)" ] && cmd=update
    npm=$(get_arg -npm)
    path=$(get_arg -path .)
    check=$(get_flag -check)
    strict=$(get_flag -strict)
    global=$(get_flag -global)
    skip=$(get_arg -skip $BKJS_MOD)
    filter=$(get_arg -filter)
    fields=$(get_arg -fields dependencies,devDependencies)
    if [[ ! -z $check ]]; then
        strict=1
        fields="$fields,modDependencies"
    else
        [[ ! -z $(get_flag -mods) ]] && fields="$fields,modDependencies"
    fi
    for p in $path; do
        m=$($NODE_BIN -e "try{skip='$skip';filter='$filter';p=require('$p/package.json');console.log('$fields'.split(',').map(f=>(Object.keys(p[f]||{}).filter(x=>((!filter||x.match(filter))&&!x.match(skip))).map(x=>(x+(!'$strict'&&p[f][x][0]=='^'?'@'+p[f][x].substr(1).split('.')[0]:'$strict'||/^[0-9]/.test(p[f][x])?'@'+p[f][x].replace(/[=<>^~]/g,''):'')).trim()).join(' '))).join(' '))}catch(e){if('$BKJS_DEBUG')console.error(e)}")
        [ "$m" != "" ] && modules="$modules $m"
    done
    [[ -z $modules ]] && exit 0
    if [ ! -z $check ]; then
        npath=./node_modules
        [ ! -z $global ] && npath=$NODE_PATH
        mods=""
        for m in $modules; do
            $NODE_BIN -e "m='$m',p=m.split('@').slice(0,-1).join('@');try{var v=require('$npath/'+p+'/package.json').version}catch(e){console.error(e)};l=child_process.execSync('npm v '+p+' version').toString().trim();console.log(v!=l?'!':'',m,v,l)"
        done
        exit 0
    fi
    [ ! -z $global ] && npm="$npm -g"
    echo "$NPM_BIN $npm $cmd $modules"
    [ ! -z "$(get_flag -dry-run)" ] && exit 0
    $NPM_BIN $npm $cmd $modules
    exit
    ;;

  help)
    echo
    echo "  deps [-fields dependencies,devDependencies] [-path .] [-skip REGEXP] [-global] [-update] [-mods] [-strict] [-check] [-npm ARGS] - install or show npm dependencies from the package.json, optional bkjs modules require -mods flag"
    ;;
    
esac
