#!/bin/sh
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Aug 2024
#

case "$BKJS_CMD" in

  help|docker-help)
    echo ""
    echo "  ecs-setup-agent - setup ECS agent to start in the current runlevel later, updates iptables"
    echo "  ecs-start-agent - start ECS agent as a docker container if not running, start docker if not running"
    echo "  ecs-stop-agent - stop ECS agent"
    ;;

  ecs-setup-agent)
    sysctl -w net.ipv4.conf.all.route_localnet=1
    iptables -t nat -A PREROUTING -p tcp -d 169.254.170.2 --dport 80 -j DNAT --to-destination 127.0.0.1:51679
    iptables -t nat -A OUTPUT -d 169.254.170.2 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 51679

    mkdir -p /etc/ecs/ /var/log/ecs /var/lib/ecs/data
    touch /etc/ecs/ecs.config

    conf=/etc/monit.d/ecs-agent.conf
    if [ ! -f $conf ]; then
        msg Setup ECS agent...

        $BKJS_BIN setup-rsyslog-docker -tag ID
        killall -HUP rsyslogd

        mkdir -p /etc/monit.d
        cycles=$(get_arg -cycles 2)
        cycles2=$(( $cycles*2 ))
        echo "check program ecs-agent with path \"$BKJS_BIN ecs-start-agent\" every $cycles cycles" >$conf
        echo "  if status != 0 for 2 times within ${cycles2} cycles then alert" >> $conf

        rc-update add docker
    fi
    exit
    ;;

  ecs-start-agent)
    if ! rc-service docker status; then
        rc-service docker start
        exit 0
    fi

    if docker top ecs-agent; then
        exit 0
    fi

    cluster=$(imds meta-data/tags/instance/ECS_CLUSTER)

    exec docker run -d --name ecs-agent \
      --restart=unless-stopped \
      --volume=/var/run:/var/run \
      --volume=/var/log/ecs/:/log \
      --volume=/var/lib/ecs/data:/data \
      --volume=/etc/ecs:/etc/ecs \
      --volume=/sbin:/host/sbin \
      --volume=/lib:/lib \
      --volume=/usr/lib:/usr/lib \
      --volume=/proc:/host/proc \
      --volume=/sys/fs/cgroup:/sys/fs/cgroup \
      --net=host \
      --env-file=/etc/ecs/ecs.config \
      --env=ECS_CLUSTER=${cluster:-default} \
      --env=ECS_LOGFILE=/log/ecs-agent.log \
      --env=ECS_DATADIR=/data \
      --env=ECS_ENABLE_TASK_IAM_ROLE=true \
      --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
      --env=ECS_AVAILABLE_LOGGING_DRIVERS='["json-file","awslogs","syslog","none"]' \
      --env=ECS_ENABLE_AWSLOGS_EXECUTIONROLE_OVERRIDE=true \
      --cap-add=sys_admin \
      --cap-add=net_admin \
      public.ecr.aws/ecs/amazon-ecs-agent:latest
    ;;

  ecs-stop-agent)
    exec docker rm -f ecs-agent
    ;;
    
esac
