#!/bin/bash
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

CWAGENT=amazon-cloudwatch-agent
CWAROOT=/opt/aws/$CWAGENT

case "$BKJS_CMD" in

  help|ec2-help)
    echo ""
    echo "  ec2-cwagent-get - install AWS Cloudwatch agent"
    echo "  ec2-cwagent-check-config [-root D] - check AWS Cloudwatch agent config for changes, exists with code 2 if changed"
    echo "  ec2-cwagent-start [-root D] - start AWS Cloudwatch agent"
    echo "  ec2-cwagent-init-monit [-root D] - setup agent to be run on start and to be monitored"
    ;;

  ec2-cwagent-get)
    root=$(get_arg -root $CWAROOT)
    if [ ! -d $root ]; then
        case "$OS_TYPE" in
          alpine)
            mkdir -p $root/bin $root/etc/$CWAGENT.d $root/logs $root/var
            (cd $root/bin &&
                curl -OL https://amazoncloudwatch-agent.s3.amazonaws.com/nightly-build/latest/linux_$OS_ARCH/amazon-cloudwatch-agent &&
                curl -OL https://amazoncloudwatch-agent.s3.amazonaws.com/nightly-build/latest/linux_$OS_ARCH/config-translator &&
                chmod 755 $root/bin/*)
            ;;

          amazon)
            curl -OL https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/$OS_ARCH/latest/amazon-cloudwatch-agent.rpm
            rpm -i amazon-cloudwatch-agent.rpm
            rm amazon-cloudwatch-agent.rpm
            ;;
        esac
    fi
    exit
    ;;

  ec2-cwagent-start)
    root=$(get_arg -root $CWAROOT)
    [ ! -d $root ] && exit 2

	tag=$(get_arg -tag)
	[ -z "$tag" ] && tag=$($BKJS_BIN ec2-tag)

    files="access.log message.log error.log $BKJS_CLOUDWATCH_LOGS"
    for log in $files; do
        [ -n "$logs" ] && logs="$logs,"
        logs="$logs{ \"file_path\": \"$BKJS_HOME/log/$log\", \"log_group_name\": \"$log\", \"log_stream_name\": \"$tag\", \"multi_line_start_pattern\": \"^[^ \\t]\", \"timestamp_format\": \"%Y-%m-%dT%H:%M:%S.%f\" }"
    done
    tmp=$root/etc/cwagent.json
    echo "{ \"agent\": { \"usage_data\": false, \"logfile\": \"$CWAROOT/logs/cwagent.log\" }, \"logs\": { \"logs_collected\": { \"files\": { \"collect_list\": [ $logs ] } }, \"log_stream_name\": \"$tag\" } }" > $tmp

    json=$root/etc/$CWAGENT.json
    toml=$root/etc/$CWAGENT.toml

    cmp $json $tmp
    if [ "$?" != "0" ]; then
    	mv $tmp $json
    	$root/bin/config-translator --input $json --output $toml --mode auto
    	[ "$?" != "0" ] && exit 1
    fi

    toml=$root/etc/$CWAGENT.toml
    env=$root/etc/env-config.json
    echo "{ \"CWAGENT_LOG_LEVEL\": \"$(get_arg -log ERROR)\" }" > $env

    exec nohup $root/bin/$CWAGENT -config $toml -envconfig $env -pidfile $root/logs/cwagent.pid >> $CWAROOT/logs/cwagent.log 2>&1 &
    exit 0
    ;;

  ec2-cwagent-init-monit)
	root=$(get_arg -root $CWAROOT)
	echo -e "check process cwagent with pidfile $root/logs/cwagent.pid start program = \"$BKJS_BIN ec2-cwagent-start\" as uid $BKJS_USER stop program = \"/usr/bin/pkill -f $CWAGENT\"" > /etc/monit.d/cwagent.conf
	exit
	;;

esac
