#!/bin/sh
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Nov 2021
#

case "$BKJS_CMD" in

  docker-build)
    tag=$(get_arg -tag)
    version=$(get_arg -version)
    path=$(get_arg -path .)
    root=$(get_arg -root .)

    [ ! -f $path/Dockerfile.$tag ] && echo "$BKJS_CMD: no Dockerfile.$tag found in $path" && exit 1

    [ -f $path/path.$tag ] && path="$root$(head -1 $path/path.$tag)"
    [ ! -d $root ] && echo "$BKJS_CMD: invalid $tag context path: $root" && exit 1

    if [ ! -f $root/.dockerignore ]; then
        if [ -f $path/dockerignore.$tag ]; then
            cp $path/dockerignore.$tag $root/.dockerignore
        else
            echo '*' > $root/.dockerignore
        fi
        dockerignore=yes
    fi

    [ -f $path/build.$tag ] && cmd=$(cat $path/build.$tag|tr '\n' ' ')
    [ ! -z $version ] && cmd="$cmd -t $tag:$version"

    cmd="docker build --rm --progress=plain -t $tag -f $path/Dockerfile.$tag $cmd $root"
    [ ! -z "$BKJS_DEBUG" ] && echo $cmd

    $cmd
    rc=$?

    [ "$dockerignore" = "yes" ] && rm -f $root/.dockerignore
    [ "$rc" != "0" ] && exit $rc

    [ "$(get_flag -run)" != "" ] && $0 docker-run -tag $tag -path $path -force
    exit
    ;;

  docker-run)
    tag=$(get_arg -tag)
    path=$(get_arg -path .)

    [ -z $tag ] && echo "$BKJS_CMD: -tag must be provided" && exit 1
    [ -f $path/run.$tag ] && cmd=$(cat $path/run.$tag|tr '\n' ' ')

    if [ "$(get_flag -force)" != "" ]; then
       pids=$(docker ps -aq -f name=$tag)
       [ ! -z $pids ] && docker rm -f $pids
    fi

    cmd="docker run -d --name $tag ${cmd:-$tag} $(get_all_args "-tag -path -force")"
    [ ! -z "$BKJS_DEBUG" ] && echo $cmd

    $cmd
    exit
    ;;

  docker-init-rsyslog)
    if [ "$(grep -s "#Bkjs $BKJS_HOME" /etc/rsyslog.d/bkjs-docker.conf)" = "" ]; then
       echo "Configuring rsyslog.d/$BKJS-docker ..."
       echo "#Bkjs $BKJS_HOME" > /etc/rsyslog.d/$BKJS-docker.conf
       echo "\$FileOwner $BKJS_USER" >> /etc/rsyslog.d/$BKJS-docker.conf
       bkjsfmt=""
       if [ -d /etc/systemd ]; then
          echo '$template bkjsfmt2,"%APP-NAME% %msg%\n"' >> /etc/rsyslog.d/$BKJS-docker.conf
          bkjsfmt=";bkjsfmt2"
       fi
       echo "local1.* $BKJS_HOME/log/docker.log$bkjsfmt" >> /etc/rsyslog.d/$BKJS-docker.conf

       echo '{ "features": { "buildkit": true }, "log-driver": "syslog", "log-opts": { "tag": "{{.Name}}", "syslog-facility": "local1", "cache-disabled": "true", "mode": "non-blocking" } }' > /etc/docker/daemon.json
    fi
    exit
    ;;

  docker-restart)
    exec docker restart $BKJS_ARGV0
    ;;

  help)
    echo ""
    echo "  docker-init-rsyslog - store docker container logs in $BKJS_HOME/log/docker.log"
    echo "  docker-build -t TAG [-version V] [-path .] [-root H] - build an image for the specified tag"
    echo "  docker-run -t TAG [-path .] [-force] - run a container for the specified tag"
    echo "  docker-restart NAME - restart a container, for use with bkrsync"
    ;;
esac
