#!/bin/bash
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

case "$BKJS_CMD" in
  config-get)
    val=$($0 shell -db-get -table bk_config -log none -ipc-none -no-modules -no-db-config -db-no-cache-columns -db-local-tables -format text -cols value type ${BKJS_ARGS[0]} name ${BKJS_ARGS[1]})
    [[ ! -z $val ]] && echo $val
    exit
    ;;

  get-nats)
    platform=$(echo $PLATFORM | tr [:upper:] [:lower:])
    arch=$OS_ARCH
    [ "$arch" = "x64" ] && arch=amd64
    curl -L -o /tmp/nats.tgz https://github.com/nats-io/nats-server/releases/download/v2.9.15/nats-server-v2.9.15-$platform-$arch.tar.gz
    tar --strip-components=1 -C /tmp -xzf /tmp/nats.tgz
    mv /tmp/nats-server $BKJS_PREFIX/bin
    rm -rf /tmp/nats.tgz
    if [ ! -f $BKJS_HOME/etc/nats.conf ]; then
        echo 'listen: localhost:4222' >> $BKJS_HOME/etc/nats.conf
        echo 'http: localhost:8222' >> $BKJS_HOME/etc/nats.conf
        echo 'syslog: true' >> $BKJS_HOME/etc/nats.conf
        echo 'logtime: false' >> $BKJS_HOME/etc/nats.conf
        echo "pid_file: $BKJS_HOME/var/nats.pid" >> $BKJS_HOME/etc/nats.conf
        echo 'jetstream: {' >> $BKJS_HOME/etc/nats.conf
        echo "  store_dir: \"$BKJS_HOME/var\"" >> $BKJS_HOME/etc/nats.conf
        echo '  max_file: 1G' >> $BKJS_HOME/etc/nats.conf
        echo '}' >> $BKJS_HOME/etc/nats.conf
        echo 'cluster {' >> $BKJS_HOME/etc/nats.conf
        echo '  name: nats' >> $BKJS_HOME/etc/nats.conf
        echo '  #listen: 0.0.0.0:6222' >> $BKJS_HOME/etc/nats.conf
        echo '  routes: [' >> $BKJS_HOME/etc/nats.conf
        echo '    nats-route://nats:6222' >> $BKJS_HOME/etc/nats.conf
        echo '  ]' >> $BKJS_HOME/etc/nats.conf
        echo '}' >> $BKJS_HOME/etc/nats.conf
    fi
    exit
    ;;

  get-natscli)
    platform=$(echo $PLATFORM | tr [:upper:] [:lower:])
    arch=$OS_ARCH
    [ "$arch" = "x64" ] && arch=amd64
    curl -L -o /tmp/nats.zip https://github.com/nats-io/natscli/releases/download/v0.0.35/nats-0.0.35-$platform-$arch.zip
    unzip -j /tmp/nats.zip -d /tmp '*/nats'
    mv /tmp/nats $BKJS_PREFIX/bin
    rm -rf /tmp/nats.zip
    exit
    ;;

  run-nats)
    name=$(get_arg -name $(uname -n|cut -f1 -d.))
    mkdir -p $BKJS_HOME/var $BKJS_HOME/log
    exec nohup nats-server -n $name -c $BKJS_HOME/etc/nats.conf >>$BKJS_HOME/log/message.log 2>&1 &
    exit
    ;;

  stop-nats)
    pkill -f nats
    exit
    ;;

  init-nats-monit)
    $0 init-monit -name nats -start "$BKJS_BIN run-nats" -stop "$BKJS_BIN stop-nats"
    monit reload
    exit
    ;;

  init-dynamodb)
    ($0 get-dynamodb $(get_all_args))
    ($0 run-dynamodb $(get_all_args))
    exit
    ;;

  get-dynamodb)
    [ "$DYNAMODB_PREFIX" = "" ] && DYNAMODB_PREFIX=$BKJS_PREFIX/dynamodb
    [ "$(get_flag -force)" != "" -a "$DYNAMODB_PREFIX" != "" ] && rm -rf $DYNAMODB_PREFIX
    if [ ! -d $DYNAMODB_PREFIX ]; then
       mkdir -p $DYNAMODB_PREFIX
       curl -L -o ddb.tgz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
       tar -C $DYNAMODB_PREFIX -xzf ddb.tgz
       rm -f ddb.tgz
    fi
    exit
    ;;

  run-dynamodb)
    [ "$DYNAMODB_PREFIX" = "" ] && DYNAMODB_PREFIX=$BKJS_PREFIX/dynamodb
    mkdir -p $BKJS_HOME/var $BKJS_HOME/log
    params="-Xmx$(get_arg -memmax 256M)"
    exec nohup java $params -Djava.library.path=$DYNAMODB_PREFIX/DynamoDBLocal_lib -jar $DYNAMODB_PREFIX/DynamoDBLocal.jar -dbPath $BKJS_HOME/var -port 8181 >>$BKJS_HOME/log/ddb.log 2>&1 &
    exit
    ;;

  stop-dynamodb)
    pkill -f DynamoDBLocal
    exit
    ;;

  reset-dynamodb)
    $0 stop-dynamodb
    rm -rf $BKJS_HOME/var/*_us-east-1.db
    $0 run-dynamodb
    exit
    ;;

  get-mvn)
    [ "$MVN_PREFIX" = "" ] && MVN_PREFIX=$BKJS_PREFIX/mvn
    [ "$(get_flag -force)" != "" -a "$MVN_PREFIX" != "" ] && rm -rf $MVN_PREFIX
    if [ ! -d $MVN_PREFIX ]; then
        curl -L -o mvn.tgz ftp://mirror.csclub.uwaterloo.ca/apache/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
        mkdir -p $MVN_PREFIX
        tar -C $MVN_PREFIX --strip-components=1 -xzf mvn.tgz
        rm -f mvn.tgz
    fi
    exit
    ;;

  init-pgsql)
    PG_DIR=$BKJS_HOME/var/postgres
    if [ ! -f $PG_DIR/postgresql.conf ]; then
       db=$(get_arg -db backend)
       mkdir -p $PG_DIR
       initdb -U postgres -D $PG_DIR
       $SED "s/#fsync = on/fsync = off/g" $PG_DIR/postgresql.conf
       $SED "s/#log_destination = 'stderr'/log_destination = 'syslog'/g" $PG_DIR/postgresql.conf
       postgres -F -D $PG_DIR &
       sleep 3
       createdb -U postgres $db
    fi
    exit
    ;;

  run-pgsql)
    mkdir -p $BKJS_HOME/var $BKJS_HOME/log
    exec nohup postgres -F -D $BKJS_HOME/var/postgres >>$BKJS_HOME/log/message.log 2>&1 &
    exit
    ;;

  stop-pgsql)
    killall postgres
    exit
    ;;

  run-crdb)
    mkdir -p $BKJS_HOME/var $BKJS_HOME/log
    if [ ! -d $BKJS_HOME/var/crdb ]; then
        db=$(get_arg -db backend)
        cockroach start --insecure --store=$BKJS_HOME/var/crdb --log-dir $BKJS_HOME/log --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
        sleep 3
        cockroach init --insecure --host=localhost:26257
        sleep 3
        cockroach sql --insecure --host=localhost:26257 -e "CREATE USER IF NOT EXISTS postgres;CREATE DATABASE $db;GRANT ALL ON DATABASE $db TO postgres;"
    fi
    exit
    ;;

  demo-crdb)
    cockroach demo --no-example-database --insecure
    ;;


  shell-crdb)
    cockroach sql --insecure --host=localhost:26257 $(get_all_args)
    exit
    ;;

  stop-crdb)
    killall cockroach
    exit
    ;;

  init-mysql)
    [ "$MYSQL_DIR" = "" ] && MYSQL_DIR=$BKJS_HOME/var/mysql
    if [ ! -d $MYSQL_DIR ]; then
       db=$(get_arg -db backend)
       mkdir -p $MYSQL_DIR
       $ECHO "[client]\nuser=root\ndatabase=$db\nport=3306\nsocket=$MYSQL_DIR/mysql.sock\n\n" > ~/.my.cnf
       $ECHO "[mysqld]\nport=3306\nsocket=$MYSQL_DIR/mysql.sock\ndatadir=$MYSQL_DIR\nkey_buffer_size=16M\nmax_allowed_packet=500M\ngroup_concat_max_len=16000\n" >> ~/.my.cnf
       mysql_install_db --force --skip-name-resolve --datadir=$MYSQL_DIR --defaults-file=$HOME/.my.cnf
       ($0 run-mysql)
       sleep 5
       mysql -u root -e "DELETE FROM user WHERE user=''" mysql
       mysql -u root -e "DROP DATABASE test" mysql
       mysql -u root -e "CREATE DATABASE $db" mysql
    fi
    exit
    ;;

  run-mysql)
    mkdir -p $BKJS_HOME/var $BKJS_HOME/log
    exec nohup mysqld >>$BKJS_HOME/log/message.log 2>&1 &
    exit
    ;;

  stop-mysql)
    killall mysqld
    exit
    ;;

  get-mongodb)
    case "$PLATFORM" in
     Darwin)
       OS=osx
       ;;
     Linux)
       OS=linux
       ;;
    esac
    if [ ! -f $BKJS_PREFIX/bin/mongod ]; then
       curl -L -o mongo.tgz http://fastdl.mongodb.org/osx/mongodb-$OS-x86_64-3.0.6.tgz
       tar -C $BKJS_PREFIX/bin --strip-components=1 -xzf mongo.tgz '*/bin/*'
       rm -rf mongo.tgz
    fi
    exit
    ;;

  init-mongodb)
    ($0 get-mongodb)
    ($0 run-mongodb)
    exit
    ;;

  run-mongodb)
    [ "$MONGO_DIR" = "" ] && export MONGO_DIR=$BKJS_HOME/var/mongo
    mkdir -p $MONGO_DIR $BKJS_HOME/var $BKJS_HOME/log
    mongod --fork --dbpath $MONGO_DIR --syslog >>$BKJS_HOME/log/message.log 2>&1
    exit
    ;;

  stop-mongodb)
    pkill mongod
    exit
    ;;

  get-amqp)
    [ "$RABBITMQ_PREFIX" = "" ] && RABBITMQ_PREFIX=$BKJS_PREFIX/rabbitmq
    [ "$(get_flag -force)" != "" -a "$RABBITMQ_PREFIX" != "" ] && rm -rf $RABBITMQ_PREFIX
    if [ ! -d $RABBITMQ_PREFIX ]; then
        mkdir -p $RABBITMQ_PREFIX/var
        curl -L -o mq.tar.xz https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.14/rabbitmq-server-generic-unix-3.8.14.tar.xz
        tar -C $RABBITMQ_PREFIX --strip-components=1 -xzf mq.tar.xz
        rm -rf mq.tar.xz
    fi
    exit
    ;;

run-amqp)
    [ "$RABBITMQ_PREFIX" = "" ] && RABBITMQ_PREFIX=$BKJS_PREFIX/rabbitmq
    $RABBITMQ_PREFIX/sbin/rabbitmq-server -detached >>$BKJS_HOME/log/message.log 2>&1
    exit
    ;;

  help)
    echo ""
    echo "Servers and tools commands:"
    echo ""
    echo "  config-get TYPE NAME - return the value for the given config record"
    echo "  init-dynamodb - download and install local DynamoDB, start the server"
    echo "  get-dynamodb [-force] - install local DynamoDB server in $BKJS_PREFIX/dynamodb"
    echo "  run-dynamodb [-memmax SZ] - run local DynamoDB server installed in $BKJS_PREFIX/dynamodb, data files in $BKJS_HOME/var"
    echo "  stop-dynamodb - stop local DynamoDB server"
    echo "  reset-dynamodb - remove local DynamoDB database and restart the server"
    echo "  run-crdb - run local CockroachDB server"
    echo "  stop-crdb - stop local CockroachDB server"
    echo "  shell-crdb - run local CockroachDB sql shell"
    echo "  init-pgsql [-db NAME] - setup and run the PostgreSQL server, data files in $BKJS_HOME/var, create initial database"
    echo "  run-pgsql - run local PostgreSQL server"
    echo "  stop-pgsql - stop local PostgreSQL server"
    echo "  init-mysql [-db DB] - setup MySQL server for development and create initial database, start the server"
    echo "  run-mysql - run local MySQL server"
    echo "  stop-mysql - stop local MySQL server"
    echo "  init-mongodb - download and start the Mongo server"
    echo "  get-mongodb - download Mongo server and install in $BKJS_PREFIX/bin"
    echo "  run-mongodb - run local Mongo server installed in $BKJS_PREFIX/bin, db path is $BKJS_HOME/var"
    echo "  stop-mongodb - stop local Mongo server"
    echo "  get-amqp [-force] - install local RabbitMQ server in $BKJS_PREFIX/rabbitmq"
    echo "  run-amqp - run local RabbitMQ server installed in $BKJS_PREFIX/rabbitmq"
    echo "  get-nats - install local NATS server in $BKJS_PREFIX/bin"
    echo "  get-natscli - install NATS command line tool in $BKJS_PREFIX/bin"
    echo "  run-nats - run local NATS server installed in $BKJS_PREFIX/bin"
    echo "  stop-nats - stop local NATS server"
    ;;
esac

