#!/bin/sh
#
#  Author: Vlad Seryakov vseryakov@gmail.com
#  Sep 2013
#

case "$BKJS_CMD" in

  help|deps-help)
    echo
    echo "  deps [-path .] [-dirs LIST] [-skip REGEXP] [-install] [-global] [-update] [-dev] [-peer] [-optional] [-strict] [-npm ARGS] - show or install packages from the a path/package.json or a directory with many packages(workspace), install all found packages directly with specific versions"
    ;;

  deps)
    NPM_BIN=$BKJS_HOME/bin/npm
    [ ! -f $NPM_BIN ] && NPM_BIN=$(which npm 2>/dev/null)
    cmd=install
    [ -n "$(get_flag -update)" ] && cmd=update
    npmargs=$(get_arg -npm)
    install=$(get_flag -install)
    strict=$(get_flag -strict)
    global=$(get_flag -global)
    skip=$(get_arg -skip)
    filter=$(get_arg -filter)
    fields=$(get_arg -fields dependencies)
    if [[ -z "$install" ]]; then
        strict=1
        fields="$fields,devDependencies,optionalDependencies,peerDependecies"
    else
        [ -n "$(get_flag -optional)" ] && fields="$fields,optionalDependencies"
        [ -n "$(get_flag -peer)" ] && fields="$fields,peerDependencies"
        [ -n "$(get_flag -dev)" ] && fields="$fields,devDependencies"
    fi
    path=$(get_arg -path)
    dirs=$(get_arg -dirs)
    if [ -n "$dirs" ]; then
        depth=$(get_arg -depth 1)
        path=$(find $dirs -maxdepth $depth -mindepth 1 -type d)
    fi
    for p in ${path:-.}; do
        [ ! -f $p/package.json ] && continue
        [[ "${p:0:1}" != "/" && "${p:0:1}" != "." ]] && p="./$p"
        m=$(node -e "try{skip='$skip';filter='$filter';p=require('$p/package.json');console.log('$fields'.split(',').map(f=>(Object.keys(p[f]||{}).filter(x=>((!filter||x.match(filter))&&!(skip&&x.match(skip)))).map(x=>(x+(!'$strict'&&p[f][x][0]=='^'?'@'+p[f][x].substr(1).split('.')[0]:'$strict'||/^[0-9]/.test(p[f][x])?'@'+p[f][x].replace(/[=<>^~]/g,''):'')).trim()).join(' '))).join(' '))}catch(e){if('$BKJS_DEBUG')console.error('$p',e)}")
        [ "$m" != "" ] && modules="$modules $m"
    done
    [ -z "$modules" ] && exit 0
    if [ -z "$install" ]; then
        npath=./node_modules
        [ -n "$global" ] && npath=$BKJS_HOME/lib/node_modules
        mods=""
        for m in $modules; do
            node -e "m='$m',p=m.split('@').slice(0,-1).join('@');try{var v=require('$npath/'+p+'/package.json').version}catch(e){console.error(e)};l=child_process.execSync('npm v '+p+' version').toString().trim();console.log(v!=l?'!':'',m,v,l)"
        done
        exit 0
    fi
    [ -n "$global" ] && npmargs="$npmargs -g"
    echo "$NPM_BIN $npmargs $cmd $modules"
    [ -z "$install" ] && exit 0
    $NPM_BIN $npmargs $cmd $modules
    exit
    ;;

esac
