
app-log=info

# connect to node repl to access web process
app-repl-port-web=2090

# redirect /app endpoints to the main index
middleware-routing-enable = true
middleware-routing-/app = /index.html
middleware-routing-/app/* = /index.html

middleware-static-enable = true
middleware-body-enable = true

files-root = var

# make sqlite database as primary
[roles!=pg]
db-pool=sqlite
db-sqlite-pool=var/kanban

# PostgreSQL
[roles=pg]
db-pool=pg
db-pg-pool=default

[global]

