ARG ALPINE=3.22

FROM alpine:$ALPINE

RUN apk --no-cache add \
  alpine-conf \
  alpine-sdk \
  apk-tools \
  coreutils \
  cmake \
  doas-sudo-shim \
  ccache \
  mc \
  nodejs \
  npm \
  python3 \
  go \
  curl \
  file \
  zip \
  rsync \
  zlib-dev \
  zimg-dev \
  fontconfig-dev \
  freetype-dev \
  imlib2-dev \
  nasm && \
  apk -U upgrade -a

RUN adduser -D alpine && \
    addgroup alpine abuild && \
    echo 'alpine ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    node-gyp install
